<div id="productos" class="productos">
    <div class="linea_productos">
        <img class="izquierda" src="/img/combo-express/combo_pizza.png">
        <img class="derecha" src="/img/combo-express/combo_pollo_frito.png">
    </div>
    <div class="linea_productos">
        <img class="izquierda" src="/img/combo-express/combo_hamburguesa.png">
        <img class="derecha" src="/img/combo-express/combo_lomiton.png">
    </div>
    <div class="linea_productos">
        <img src="/img/combo-express/combo_caesar_salab.png">
    </div>
</div>