<div class="nuestra_empresa">
    <div class="texto">
        <h1 class="titulo">Nuestra Empresa</h1>
        <p>
            Bajo un nuevo concepto de punto de venta y delivery en forma exclusiva llega COMBO EXPRESS como una
            nueva alternativa gastronómica, dándole el toque gourmet de una comida de primer nivel al fast food,
            para que el cliente pueda saborear un producto de alta calidad desde la comodidad de su hogar.
        </p>
        </br>
        <p>
            Nuestras Instalaciones cuentan con una cocina de última generación donde la
            pulcritud, la limpieza y la calidad son nuestras principales herramientas, liderado por un
            Chef profesional con experencia Internacional liderando el equipo de cocina.
        </p>
        </br>
        <p>
            No vendemos solo comida, vendemos la experiencia de adquirir productos de
            calidad y buen sabor con recetas 100% originales, llevándole directamente desde la
            cocina del chef a su hogar con la modalidad Free Delivery (entrega gratuita)
        </p>
        </br>
        <p>Y lo más importante, somos una empresa 100% Paraguaya.</p>
    </div>
</div>
