<div id="bloque_titulo">
    <h1 class="titulo_izquierda">Acceso</h1>
    
</div>
<div id="bloque_acceso">
    <h2 class="subtitulo">Acceso Operadoras</h2>
    <form id="form_acceso" action="/login" method="post">
        <div class="item_formulario"><input type="text" name="login_user" id="login_user" placeholder="User:"></div>
        <div class="item_formulario"><input type="password" name="login_pass" id="login_pass" placeholder="Pass:"></div>
        <input type="image" src="/img/boton-enviar.png" value="Enviar">
    </form>

    <h3>Entermóvil - Oficina Central</h3>
    <p>Parirí No: 834</p>
    <p>Telefax: +595 21 558 627</p>
    <p>Asunción - Paraguay</p>
</div>
