<div id="bloque_condiciones">

    <h1><?php echo $this->promo['encabezado']?>.</h1>
    <p>Organizador: ENTERMOVIL S.A.
        Licenciatario de Audio Texto – Resolución CONATEL N° 53/2013</p>
    <p>1. Quienes pueden participar:</p>
    <p>Promoción <?php echo $this->promo['encabezado']?> es una acción promocional con cargo adicional sobre la tarifa de mensajería básica, dirigida a todos aquellos usuarios mayores de edad de telefonía celular, a ser habilitada a través de la numeración corta 6767 con destino a las Operadoras de Telefonía Celular: Telecel S.A. (TIGO) y Núcleo S.A. (PERSONAL).</p>
    <p>2. Duración:</p>
    <p>La presente promoción tendrá una duración de  <?php echo $this->promo['duracion']?> meses, iniciando el 3 de Junio y culminando el 30 de Agosto de 2013, salvo que el Organizador considere conveniente su cancelación antes de cumplido el plazo o su renovación, una vez producido su término. Las bases y condiciones de esta Promoción están disponibles en la página web www.entermovil.com.py</p>
    <p>3. Mecánica de la Promoción:</p>
    <p>Los usuarios podrán generar cupones participando con la siguiente mecánica:

        A – Enviando un mensaje de texto con el ALIAS habilitado para participar de la PROMOCION, en este caso los ALIAS asignados son: <?php echo $this->promo['aliases']?>.

        B – Los ALIAS serán enviados al sistema de datos del proveedor a través de la red celular y el sistema responderá de manera automática con la Bienvenida y el mensaje de AYUDA, a fin que el usuario tenga presente que la referida promoción es por la vía de la suscripción.

        C – Una vez recibido el mensaje de Bienvenida que también informa al usuario la confirmación de su suscripción a la promoción, el mismo empieza a participar recibiendo todos los días 2 (dos) mensajes de texto cuyo costo es de Gs. 990 (Novecientos noventa guaraníes) IVA Incluido, cada uno, con el texto de que acumula 3 (tres) cupones por cada mensaje cobrado y recibido. Asimismo en el mensaje recibirá consejos de salud, cultura general, etc.

        D  – A través del comando de AYUDA el usuario tendrá la información para cancelar su suscripción a la promoción. El usuario podrá cancelar su suscripción de manera automática y en el instante en que decida hacerlo según las instrucciones indicadas en el comando de AYUDA. </p>
    <p>4. Cupones:</p>
    <p>Los cupones serán generados automáticamente en formato electrónico, no impreso, identificando el número de celular como identidad de cada participante. Los cupones son acumulativos por mes y suman según la cantidad de veces que el usuario recibe así como la cantidad de cupones por cada mensaje cobrado y recibido por el usuario.</p>
    <p>5. Sorteo:</p>
    <p>El Sorteo será realizado  el último día hábil de cada mes -Junio, Julio y Agosto- entre todos los usuarios participantes sin excepción. Los usuarios que cancelaron su suscripción también participan del sorteo, pero sólo con la cantidad de cupones que tuvieran acumulados, vigentes al día del sorteo.

        El sorteo se realizará en las oficinas de ENTERMOVIL S.A., en presencia de los organizadores y responsables de la presente promoción. Los ganadores serán informados al momento del sorteo y una vez confirmada su identidad personal serán convocados para retirar su premio en las oficinas mencionadas más arriba, ubicadas en Alonso Rodríguez N° 834 – Asunción.

        En caso de que el organizador del sorteo no logre confirmar la identidad del número de teléfono adjudicado o le fuese imposible contactar con el titular del número adjudicado, volverá a sortear el citado premio hasta lograr la adjudicación del mismo para alguno de los usuarios participantes.</p>
    <p>6. Premiación:</p>
    <p><?php echo $this->promo['premiacion']?>.

        Para efectivizar el premio el participante ganador debe presentarse con su aparato telefónico desde cuya línea se suscribió, y su cédula de identidad, en las oficinas de ENTERMOVIL S.A.

        El ganador podrá retirar su premio hasta 60 (sesenta) dias luego de  recibida la comunicación de haber sido adjudicado, en caso contrario, el premio quedará a disposición del Organizador, para la correspondiente donación establecida en el Art. 19 de la Ley N° 1016/1997.</p>
    <p>7. Excepciones:</p>
    <p>No podrán participar de la promoción ni verse beneficiados, los directivos y empleados de ENTERMOVIL S.A. ni sus parientes en 1° grado de consanguinidad y 2° de afinidad. Si resultase ganador de uno de los premios una persona prófuga o con causas pendientes con la justicia paraguaya, el sorteo de este premio será anulado y se volverá a sortear.</p>
    <p>8. Participación:</p>
    <p>El formar parte de esta promoción importa el conocimiento y aceptación de todas las condiciones establecidas en estas bases. El ganador autoriza al organizador a difundir con fines publicitarios y/o promocionales, su nombre, datos personales e imagen a través  de los medios de comunicación y por el tiempo que se considere conveniente.</p>
    <p>9. Situaciones no previstas:</p>
    <p>Cualquier situación no prevista en estas bases será resuelta por los organizadores a su solo arbitrio y sus decisiones serán irrecurribles.</p>
</div>
