<h1>Q'Somos</h1>
<p>Somos un grupo de personas que nos encanta crear medios de fácil acceso que logren divertir.</p>
<p>Contamos con talento, creatividad y conocimiento tecnológico. Fórmula mágica que hace realidad lo menos esperado.</p>
<p>Nuestra mayor satisfacción es la satisfacción de las personas que utilizan y disfrutan de nuestras creaciones.</p>
<p>Nuestro objetivo es crear, entretener, evolucionar y revolucionar todos los conceptos del entretenimiento.</p>
<p>Somos fanáticos de nuestros seguidores y queremos que ellos sean fanáticos de nuestras creaciones.</p>

<!--<p class="institucional"><img src="/img/icono-pdf.png" alt="Descarga Institucional"><a href="/institucional">Click Aquí</a> para descargar institucional.</p>-->
