<div id="bloque_titulo">
    <h1 class="titulo_izquierda">Servicios</h1>

</div>
<div id="bloque_acceso">
    <h2 class="subtitulo">35500</h2>
    <div class="bloque_servicio">
        <h1>TONO</h1>
        <h2>Tonos Inéditos</h2>
        <p>Envia TONO al 35500 y recibí los mejores Tonos Inéditos para tu celular</p>
        <p>Recibirás 5 tonos por semana. 1 tono por día. Costo por cada tono recibido de 2.200 Gs. IVA Inc.</p>
        <p>Cancelar? Envia SALIR TONO al 35500</p>
    </div>
</div>
