<form action="/index/suscripcion" method="post">
    <h4>Elegí el Servicio...</h4>
    <select name="servicio" id="servicio">
        <option value="PY">PY - Historia del Paraguay</option>
        <option value="MUNDO">MUNDO - Historia del Mundo</option>
        <option value="INGLES">INGLES - Lecciones de Inglés</option>
        <option value="OK">OK - Lecciones de Inglés</option>
        <option value="USA">USA - Lecciones de Inglés</option>
        <option value="CIENCIA">CIENCIA - Grandes Descubrimientos</option>
    </select>
    <h4>Elegí tu Operadora...</h4>
    <select name="operadora" id="operadora">
        <option value="TIGO">Tigo</option>
        <option value="PERSONAL">Personal</option>
    </select>
    <h4>Ingresá tu Número...</h4>
    <input type="text" name="cel" id="cel" value="" maxlength="10">

    <h5>Hacé click en ENVIAR</h5>
    <h6>Recibirás un mensaje de texto con un PIN para validar tu suscripción</h6>

    <input type="submit" name="enviar" value="ENVIAR">
</form>

