<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="initial-scale=1.0, width=device-width" />
    <title>ENTERMOVIL</title>
</head>
<body>

<table width="<?php echo $this->ancho_tabla ?>" border="0" cellspacing="0" cellpadding="0" id="principal" align="center">
    <!--<tr>
        <td valign="center"><img src="http://www.entermovil.com.py/<?php echo $this->ua['imagen_logo'] ?>" alt="<?php echo $this->proveedor ?>"></td>
    </tr>-->
    <tr>
        <td valign="center"><h1 style="color: black; text-align: center; padding: 0;"><?php echo $this->servicio ?></h1></td>
    </tr>
    <tr>
        <td valign="center">
            <h4 style="color: black; text-align: center; margin: 0;"><?php echo $this->descripcion ?></h4>
            <hr/>
        </td>
    </tr>
    <tr>
        <td valign="center"><h2 style="color: black; text-align: center; padding: 0;">Descargar Audio</h2></td>
    </tr>
    <tr>
        <td>
            <h2 style="color: black; text-align: center; padding: 0;">
                <a href="<?php echo $this->url_descarga ?>"><?php echo $this->nombre_archivo ?></a>
            </h2>
        </td>
    </tr>
    <tr>
        <td valign="center"><h2 style="color: black; text-align: center; padding: 0;">Texto</h2></td>
    </tr>
    <tr>
        <td valign="left"><p><?php echo $this->mensaje ?></p></td>
    </tr>

</table>

</body>
</html>

