<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="initial-scale=1.0, width=device-width" />
    <title>ENTERMOVIL</title>
</head>
<body>

<table width="<?php echo $this->ancho_tabla ?>" border="0" cellspacing="0" cellpadding="0" id="principal" align="center">
    
    <tr>
        <td valign="center"><h1 style="color: black; text-align: center; padding: 0;">Acceso Restringido</h1></td>
    </tr>
    <tr>
        <td valign="center">
            <h4 style="color: black; text-align: center; margin: 0;">Debe conectarse a la red 3G de su operadora</h4>
            <hr/>
        </td>
    </tr>

</table>

</body>
</html>

