<!--Start Breadcrumb-->
<div class="row">
    <div id="breadcrumb" class="col-xs-12">
        <ol class="breadcrumb">
            <li><a href="#">Dashboard</a></li>
            <button id="cerrar_ventana_principal" style="float: right" class="btn btn-danger">Cerrar</button>
            <button id="abrir_ventana_principal" style="float: right" class="btn btn-danger">Jugar</button>
            <button id="vaciar_localstorage" style="float: right" class="btn btn-danger">Vaciar</button>
        </ol>
    </div>
</div>
<!--End Breadcrumb-->
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-table"></i>
                    <span><strong>Tragamonedas</strong></span>
                </div>
                <div class="box-icons">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="expand-link">
                        <i class="fa fa-expand"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
                <div class="no-move"></div>
            </div>
            <div class="box-content no-padding">
                <table class="table table-striped table-bordered table-hover table-heading no-border-bottom">
                    <thead>
                        <tr>
                            <th class="col-sm-2">Preview</th>
                            <th class="col-sm-2">Cargar</th>
                            <th class="col-sm-2">Obtener Ganador</th>
                            <th class="col-sm-2">Jugar</th>
                            <th class="col-sm-3">Ganadores</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <img class="juego_preview" src="/img/tvchat/interfaz/tvchat_tragamonedas_preview.png">
                            </td>
                            <td>
                                <button id="cargar_tragamonedas" class="btn btn-primary">Cargar</button>
                                <button id="cerrar_tragamonedas" class="btn btn-primary">Quitar</button>
                            </td>
                            <td>
                                <button id="getWinElementsTragamonedas" type="button" class="btn btn-primary">Sortear</button>
                                <div id="WinElementsTragamonedas">
                                </div>
                            </td>
                            <td>
                                <button id="jugarTragamonedas" class="btn btn-primary">Jugar</button>
                            </td>
                            <td>
                                <div id="historial_tragamonedas">
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-table"></i>
                    <span><strong>Tombola</strong></span>
                </div>
                <div class="box-icons">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="expand-link">
                        <i class="fa fa-expand"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
                <div class="no-move"></div>
            </div>
            <div class="box-content no-padding">
                <table class="table table-striped table-bordered table-hover table-heading no-border-bottom">
                    <thead>
                        <tr>
                            <th class="col-sm-2">Preview</th>
                            <th class="col-sm-2">Sortear</th>
                            <th class="col-sm-3">Historial Ganadores</th>
                            <th class="col-sm-2">Cargar</th>
                            <th class="col-sm-2">Jugar</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><img class="juego_preview" src="/img/tvchat/interfaz/tvchat_tombola_preview.png"></td>
                            <td>
                                <button id="getWinElementsTombola" type="button" class="btn btn-primary">Sortear</button>
                                <div id="WinElementsTombola">
                                    <p></p>
                                </div>
                            </td>
                            <td>
                                <div id="historial_tombola">
                                </div>
                            </td>
                            <td>
                                <button id="cargar_tombola" class="btn btn-primary">Cargar</button>
                                <button id="cerrar_tombola" class="btn btn-primary">Cerrar</button>
                            </td>
                            <td><button id="jugarTombola" class="btn btn-primary">Jugar</button></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-table"></i>
                    <span><strong>Piropos</strong></span>
                </div>
                <div class="box-icons">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="expand-link">
                        <i class="fa fa-expand"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
                <div class="no-move"></div>
            </div>
            <div class="box-content no-padding">
                <table class="table table-striped table-bordered table-hover table-heading no-border-bottom">
                    <thead>
                        <tr>
                            <th class="col-sm-2">Preview</th>
                            <th class="col-sm-2">Sortear</th>
                            <th class="col-sm-3">Historial Ganadores</th>
                            <th class="col-sm-2">Cargar</th>
                            <th class="col-sm-2">Jugar</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><p style="width: 100px; height: 100px" >No disponbile</p></td>
                            <td>
                                <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#opciones_mensajes">
                                    Seleccionar
                                </button>
                                <button class="seleccionar btn btn-primary">mierda</button>
                            </td>
                            <td>
                                <div>
                                    <span></span>
                                </div>
                            </td>
                            <td>
                                <button id="cargar_piropo" type="button" class="btn btn-primary">Cargar</button>
                                <button id="cerrar_piropo" type="button" class="btn btn-primary">Quitar</button>
                            </td>
                            <td><button id="jugarPiropo" class="btn btn-primary">Jugar</button></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="opciones_mensajes" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div style="width: 1300px" class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Seleccione el Mensaje</h4>
            </div>
            <div class="modal-body">
                <div class="row" id="mensajes">
                    <p>Ola q ace<button data-mensaje="Ola q ace 1" class="seleccionar btn btn-primary" id="1">Seleccionar</button></p>
                    <p>Ola q ace<button data-mensaje="Ola q ace 2" class="seleccionar btn btn-primary" id="2">Seleccionar</button></p>
                    <p>Ola q ace<button data-mensaje="Ola q ace 3" class="seleccionar btn btn-primary" id="3">Seleccionar</button></p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </div>
</div>
<!--<div>
    <p>
        <button id="abrir_ventanas1">Bingo Show</button>
        <button id="cerrar_ventana1">Cerrar</button>
    </p>
    <p>
        <button id="abrir_ventana2">Afortunado Tombola</button>
        <button id="cerrar_ventana2">Cerrar</button>
    </p>
    <p>
        <button id="abrir_ventana3">Afortunado Tragamonedas</button>
        <button id="cerrar_ventana3">Cerrar</button>
    </p>
    <p>
        <button id="abrir_ventana4">Demo Galgo</button>
        <button id="cerrar_ventana4">Cerrar</button>
    </p>
    <p>
        <button id="abrir_ventana5">Demo Dados</button>
        <button id="cerrar_ventana5">Cerrar</button>
    </p>
    <p>
        <button id="abrir_ventana6">Demo Bingo</button>
        <button id="cerrar_ventana6">Cerrar</button>
    </p>
    <p>
        <button id="abrir_ventana7">Demo Slot</button>
        <button id="cerrar_ventana7">Cerrar</button>
    </p>
       <p>
            <button id="cargar_tombola">Tombola</button>
            <button id="cerrar_tombola">Quitar</button>
        </p>
        <p>
            <button id="cargar_tragamonedas">Tragamonedas</button>
            <button id="cerrar_tragamonedas">Quitar</button>
        </p>
        <p>
            <button id="cargar_tvchat">TVchat</button>
            <button id="cerrar_tvchat">Quitar</button>
        </p>
        <div>
            <input id="cargar_normal" type="text" value="">
            <a href="#" id="cargar">Cargar</a>
        </div>
</div>-->
