<!--tragamonedas-->
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-table"></i>
                    <span><strong>Tragamonedas</strong></span>
                </div>
            </div>
            <div class="box-content no-padding">
                <table class="table table-striped table-bordered table-hover table-heading tabla_tragamonedas">
                    <thead>
                        <tr>
                            <th class="col-sm-1">Preview</th>
                            <th class="col-sm-1">Modulo</th>
                            <th class="col-sm-2">Ganador</th>
                            <th class="col-sm-1">Jugar</th>
                            <th class="col-sm-1">Acciones</th>
                            <th class="col-sm-3">Historial</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td rowspan="2">
                                <img class="juego_preview" src="/img/tvchat/interfaz/tvchat_tragamonedas_preview.png">
                            </td>
                            <td rowspan="2">
                                <button id="cargar_tragamonedas" class="btn btn-primary">Cargar</button>
                                <button id="cerrar_tragamonedas" class="btn btn-primary">Quitar</button>
                            </td>
                            <td rowspan="2">
                                <button id="getWinElementsTragamonedas" type="button" class="btn btn-primary">C/ Premio</button>
                                <button id="getElementsTragamonedas" type="button" class="btn btn-primary">S/ Premio</button>
                                <div id="WinElementsTragamonedas">
                                </div>
                                <div class="premios">
                                    <select id="premios_tragamonedas" class="form-control">
                                        <option>Premios</option>
                                        <option value="500000">500.000 Gs En Efectivo</option>
                                        <option value="200000">200.000 Gs En Efectivo</option>
                                        <option value="100000">100.000 Gs En Efectivo</option>
                                    </select
                                </div>
                            </td>
                            <td rowspan="2">
                                <button id="jugarTragamonedas" class="btn btn-primary">Jugar</button>
                            </td>
                            <td>
                                <button id="stopRoulette1" class="btn btn-primary">Parar 1</button>
                                <button id="stopRoulette2" class="btn btn-primary">Parar 2</button>
                                <button id="stopRoulette3" class="btn btn-primary">Parar 3</button>
                            </td>
                            <td rowspan="2">
                                <div id="historial_tragamonedas">
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <button id="mostrarGanadorTragamonedas" class="btn btn-primary">Mostrar</button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!--tombola-->
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-table"></i>
                    <span><strong>Tombola</strong></span>
                </div>
            </div>
            <div class="box-content no-padding">
                <table class="table table-striped table-bordered table-hover table-heading no-border-bottom">
                    <thead>
                        <tr>
                            <th class="col-sm-1">Preview</th>
                            <th class="col-sm-1">Modulo</th>
                            <th class="col-sm-2">Ganador</th>
                            <th class="col-sm-1">Jugar</th>
                            <th class="col-sm-1">Acciones</th>
                            <th class="col-sm-3">Historial</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <img class="juego_preview" src="/img/tvchat/interfaz/tvchat_tombola_preview.png">
                            </td>
                            <td>
                                <button id="cargar_tombola" class="btn btn-primary">Cargar</button>
                                <button id="cerrar_tombola" class="btn btn-primary">Quitar</button>
                            </td>
                            <td>
                                <button id="getWinElementsTombola" type="button" class="btn btn-primary">C/ Premio</button>
                                <button id="getElementsTombola" type="button" class="btn btn-primary">S/ Premio</button>
                                <div id="WinElementsTombola">
                                    <p></p>
                                </div>
                                <div class="premios">
                                    <select id="premios_tombola" class="form-control">
                                        <option>Premios</option>
                                        <option value="500000">500.000 Gs En Efectivo</option>
                                        <option value="200000">200.000 Gs En Efectivo</option>
                                        <option value="100000">100.000 Gs En Efectivo</option>
                                    </select
                                </div>
                            </td>
                            <td>
                                <button id="jugarTombola" class="btn btn-primary">Jugar</button>
                            </td>
                            <td>
                                <button id="stopTombola" class="btn btn-primary">Girar</button>
                            </td>
                            <td>
                                <div id="historial_tombola">
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!--piropos-->
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-table"></i>
                    <span>
                        <strong>Piropos</strong>
                    </span>
                </div>
            </div>
            <div class="box-content no-padding">
                <table class="table table-striped table-bordered table-hover table-heading no-border-bottom">
                    <thead>
                        <tr>
                            <th class="col-sm-1">Preview</th>
                            <th class="col-sm-1">Modulo</th>
                            <th class="col-sm-2">Ganador</th>
                            <th class="col-sm-1">Jugar</th>
                            <th class="col-sm-1">Acciones</th>
                            <th class="col-sm-3">Historial</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <img class="juego_preview" src="/img/tvchat/interfaz/tvchat_piropo_preview.png">
                            </td>
                            <td>
                                <button id="cargar_piropo" class="btn btn-primary">Cargar</button>
                                <button id="cerrar_piropo" class="btn btn-primary">Quitar</button>
                            </td>
                            <td>
                                <div>
                                    <button id="seleccionar_piropo" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#opciones_mensajes">
                                        Seleccionar
                                    </button>
                                    <div id="WinElementsPiropo">
                                    </div>
                                    <div class="premios">
                                        <select id="premios_piropos" class="form-control">
                                            <option>Premios</option>
                                            <option value="50000">50.000 Gs En Saldo</option>
                                        </select
                                    </div>
                                </div>
                            </td>
                            <td>
                                <button id="jugarPiropo" class="btn btn-primary">Jugar</button>
                            </td>
                            <td></td>
                            <td>
                                <div id="historial_piropo">
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!--tragamonedas sexy-->
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-table"></i>
                    <span><strong>Tragamonedas Sexy</strong></span>
                </div>
            </div>
            <div class="box-content no-padding">
                <table class="table table-striped table-bordered table-hover table-heading no-border-bottom">
                    <thead>
                        <tr>
                            <th class="col-sm-1">Preview</th>
                            <th class="col-sm-1">Modulo</th>
                            <th class="col-sm-2">Ganador</th>
                            <th class="col-sm-1">Jugar</th>
                            <th class="col-sm-1">Acciones</th>
                            <th class="col-sm-3">Historial</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td rowspan="2">
                                <img class="juego_preview" src="/img/tvchat/interfaz/tvchat_tragamonedas_preview.png">
                            </td>
                            <td rowspan="2">
                                <button id="cargar_tragamonedas_sexy" class="btn btn-primary">Cargar</button>
                                <button id="cerrar_tragamonedas_sexy" class="btn btn-primary">Quitar</button>
                            </td>
                            <td rowspan="2">
                                <button id="getWinElementsTragamonedasSexy" type="button" class="btn btn-primary">Seleccionar</button>
                                <div id="WinElementsTragamonedasSexy"></div>
                                <div id="selectWinElements" class="selectWinElements">
                                    <div class="stop_image_number_value param_label1">
                                        <span class="param_name">Tira 1: </span> <span class="stop_image_number_param1"></span>
                                    </div>
                                    <span id="image_sample1" class="image_sample1">
                                        <img data-value="0"  src="/img/tvchat/tragamonedas/zapato.png"/>
                                        <img data-value="1"  src="/img/tvchat/tragamonedas/bombacha.png"/>
                                        <img data-value="2"  src="/img/tvchat/tragamonedas/portacena.png"/>
                                    </span>
                                    <div class="stop_image_number_value param_label2">
                                        <span class="param_name">Tira 2: </span> <span class="stop_image_number_param2"></span>
                                    </div>
                                    <span id="image_sample2" class="image_sample2">
                                        <img data-value="0"  src="/img/tvchat/tragamonedas/zapato.png"/>
                                        <img data-value="1"  src="/img/tvchat/tragamonedas/bombacha.png"/>
                                        <img data-value="2"  src="/img/tvchat/tragamonedas/portacena.png"/>
                                    </span>
                                    <div class="stop_image_number_value param_label3">
                                        <span class="param_name">Tira 3: </span> <span class="stop_image_number_param3"></span>
                                    </div>
                                    <span id="image_sample3" class="image_sample3">
                                        <img data-value="0"  src="/img/tvchat/tragamonedas/zapato.png"/>
                                        <img data-value="1"  src="/img/tvchat/tragamonedas/bombacha.png"/>
                                        <img data-value="2"  src="/img/tvchat/tragamonedas/portacena.png"/>
                                    </span>
                                </div>
                                <div class="premios">
                                    <select id="premios_tragamonedas_sexy" class="form-control">
                                        <option>Premios</option>
                                        <option value="50000">50.000 Gs En Saldo</option>
                                    </select
                                </div>
                            </td>
                            <td rowspan="2">
                                <button id="jugarTragamonedasSexy" class="btn btn-primary">Jugar</button>
                            </td>
                            <td>
                                <button id="stopRouletteSexy1" class="btn btn-primary">Parar 1</button>
                                <button id="stopRouletteSexy2" class="btn btn-primary">Parar 2</button>
                                <button id="stopRouletteSexy3" class="btn btn-primary">Parar 3</button>
                            </td>
                            <td rowspan="2">
                                <div id="historial_tragamonedas_sexy">
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <button id="mostrarGanadorTragamonedasSexy" class="btn btn-primary">Mostrar</button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="opciones_mensajes" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div style="width: 1300px" class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Seleccione el Mensaje</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <table class="table table-striped table-bordered table-hover table-heading no-border-bottom">
                        <thead>
                            <tr>
                                <th>Mensaje</th>
                                <th>Accion</th>
                            </tr>
                        </thead>
                        <tbody id="mensajes">
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

