<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Entermovil - Admin</title>

        <!-- Bootstrap Core CSS -->
        <link href="/css/plugins/bootstrap/bootstrap.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="/css/plugins/sb-admin.css" rel="stylesheet">

        <!-- Morris Charts CSS -->
        <link href="/css/plugins/morris.css" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>

    <body>

        <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Entermovil Admin</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Admin <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="/tvchat/logout/"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <ul id="conexion" class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Conexion </a>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li id="abrir_ventana_principal" class="active">
                        <a href="#ventana_principal"><i class="fa fa-fw fa-dashboard"></i>Abrir Pantalla</a>
                    </li>
                    <li id="cerrar_ventana_principal">
                        <a  href="#cerrar_ventana_principal"><i class="fa fa-fw fa-dashboard"></i>Cerrar Pantalla</a>
                    </li>
                    <li id="abrir_ventana_tvhot">
                        <a href="#ventana_tvhot"><i class="fa fa-fw fa-dashboard"></i>Abrir Tvhot</a>
                    </li>
                    <li id="cerrar_ventana_tvhot">
                        <a href="#cerrar_ventana_tvhot"><i class="fa fa-fw fa-dashboard"></i>Cerrar Tvhot</a>
                    </li>
                    <li>
                        <table class="totales table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th style="background-color: #000000; color: #ffffff" colspan="2" class="col-sm-1">Totales</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td style="background-color: #ffffff" class="col-sm-1">Total Guaranies: </td>
                                    <td style="background-color: #ffffff" class="col-sm-1" id="total_guaranies">0</td>
                                </tr>
                                <tr>
                                    <td style="background-color: #ffffff">Total Sorteos: </td>
                                    <td style="background-color: #ffffff" id="total_sorteos">0</td>
                                </tr>
                            </tbody>
                        </table>
                    </li>
                    <li id="ocultar_lineas_referencia_conductora">
                        <a href="#ocultarLineaReferencia"><i class="fa fa-fw fa-dashboard"></i>Ocultar Lineas Referencia</a>
                    </li>
                    <li id="mostrar_lineas_referencia_conductora">
                        <a href="#mostrarLineaReferencia"><i class="fa fa-fw fa-dashboard"></i>Mostrar Lineas Referencia</a>
                    </li>
                    <li id="mostrar_modulo_por_defecto">
                        <a href="#mostrar_modulo_por_defecto"><i class="fa fa-fw fa-dashboard"></i>Quitar</a>
                    </li>
                    <li id="parar_marquee">
                        <a href="#parar_marquee"><i class="fa fa-fw fa-dashboard"></i>Parar marquee</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper" style="height: 433px">

        <div class="container-fluid">

            <!-- Page Heading -->
            <!--<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        Dashboard <small>Statistics Overview</small>
                        </h1>
                    <ol class="breadcrumb">
                        <li class="active">
                            <i class="fa fa-dashboard"></i> Juegos
                        </li>
                    </ol>
                </div>
            </div>-->
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav nav-tabs">
                            <li id="mostrar_bloque_tragamonedas"><a  href="#tragamonedas">Tragamonedas</a></li>
                            <li id="mostrar_bloque_tragamonedas_sexy"><a href="#tragamonedas_sexy">Tragamonedas Sexy</a></li>
                            <li id="mostrar_bloque_tombola"><a href="#tombola">Tombola</a></li>
                            <li id="mostrar_bloque_piropo1"><a href="#piropo1">Piropo 1</a></li>
                            <li id="mostrar_bloque_piropo2"><a href="#piropo2">Piropo 2</a></li>
                            <li id="mostrar_bloque_video"><a href="#video">Video</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div>
            </div>

            <!--tragamonedas-->
            <div class="row" id="tragamonedas">
                <div class="col-xs-12">
                    <h3>Tragamonedas</h3>
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover tabla_tragamonedas">
                            <thead>
                                <tr>
                                    <th class="col-sm-1">Preview</th>
                                    <th class="col-sm-1">Modulo</th>
                                    <th colspan="2" class="col-sm-2">Ganador</th>
                                    <th class="col-sm-1">Jugar</th>
                                    <th class="col-sm-1">Acciones</th>
                                    <th class="col-sm-3">Historial</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td rowspan="4">
                                        <img class="juego_preview" src="/img/tvchat/interfaz/tvchat_tragamonedas_preview.png">
                                    </td>
                                    <td rowspan="2">
                                        <button id="cargar_tragamonedas" class="btn btn-primary">Cargar</button>
                                    </td>
                                    <td>
                                        <button id="getWinElementsTragamonedas" type="button" class="btn btn-primary">C/ Premio</button>
                                    </td>
                                    <td>
                                        <button id="getElementsTragamonedas" type="button" class="btn btn-primary">S/ Premio</button>
                                    </td>
                                    <td rowspan="4">
                                        <button id="jugarTragamonedas" class="btn btn-primary">Jugar</button>
                                    </td>
                                    <td>
                                        <button id="stopRoulette1" class="btn btn-primary">Parar 1</button>
                                    </td>
                                    <td rowspan="4">
                                        <div id="historial_tragamonedas">
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2" id="WinElementsTragamonedas">
                                    </td>
                                    <td><button id="stopRoulette2" class="btn btn-primary">Parar 2</button></td>
                                </tr>
                                <tr>
                                    <td rowspan="2"><button id="cerrar_tragamonedas" class="btn btn-primary">Quitar</button></td>
                                    <td colspan="2" id="WinPhoneNumberTragamonedas"></td>
                                    <td><button id="stopRoulette3" class="btn btn-primary">Parar 3</button></td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <div class="premios">
                                            <select id="premios_tragamonedas" class="form-control">
                                                <option>Premios</option>
                                                <option value="500000">500.000 Gs En Efectivo</option>
                                                <option value="200000">200.000 Gs En Efectivo</option>
                                                <option value="100000">100.000 Gs En Efectivo</option>
                                            </select
                                        </div>
                                    </td>
                                    <td>
                                        <button id="mostrarGanadorTragamonedas" class="btn btn-primary">Mostrar</button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <!--tombola-->
            <div class="row" id="tombola">
                <div class="col-xs-12">
                    <h3>Tombola</h3>
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th class="col-sm-1">Preview</th>
                                    <th colspan="2" class="col-sm-2">Ganador</th>
                                    <th class="col-sm-1">Modulo</th>
                                    <th class="col-sm-1">Jugar</th>
                                    <th class="col-sm-1">Acciones</th>
                                    <th class="col-sm-3">Historial</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td rowspan="4">
                                        <img class="juego_preview" src="/img/tvchat/interfaz/tvchat_tombola_preview.png">
                                    </td>
                                    <td>
                                        <button id="getWinElementsTombola" type="button" class="btn btn-primary">C/ Premio</button>
                                    </td>
                                    <td>
                                        <button id="getElementsTombola" type="button" class="btn btn-primary">S/ Premio</button>
                                    </td>
                                    <td rowspan="2">
                                        <button id="cargar_tombola" class="btn btn-primary">Cargar</button>
                                    </td>
                                    <td rowspan="4">
                                        <button id="jugarTombola" class="btn btn-primary">Jugar</button>
                                    </td>
                                    <td rowspan="4">
                                        <button id="stopTombola" class="btn btn-primary">Girar</button>
                                    </td>
                                    <td rowspan="4">
                                        <div id="historial_tombola">
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2" id="WinElementsTombola"></td>
                                </tr>
                                <tr>
                                    <td colspan="2" id="WinPhoneNumberTombola"></td>
                                    <td rowspan="2"><button id="cerrar_tombola" class="btn btn-primary">Quitar</button></td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <div class="premios">
                                            <select id="premios_tombola" class="form-control">
                                                <option>Premios</option>
                                                <option value="500000">500.000 Gs En Efectivo</option>
                                                <option value="200000">200.000 Gs En Efectivo</option>
                                                <option value="100000">100.000 Gs En Efectivo</option>
                                            </select
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <!--piropos-->
            <div class="row" id="piropo1">
                <div class="col-xs-12">
                    <h3>Piropos 1</h3>
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th class="col-sm-1">Preview</th>
                                    <th class="col-sm-1">Modulo</th>
                                    <th class="col-sm-2">Ganador</th>
                                    <th class="col-sm-1">Jugar</th>
                                    <th class="col-sm-1">Acciones</th>
                                    <th class="col-sm-3">Historial</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td rowspan="2">
                                        <img class="juego_preview" src="/img/tvchat/interfaz/tvchat_piropo_preview.png">
                                    </td>
                                    <td>
                                        <button id="cargar_piropo" class="btn btn-primary">Cargar</button>

                                    </td>
                                    <td>
                                        <button id="seleccionar_piropo" class="btn btn-primary" data-toggle="modal" data-target="#opciones_mensajes">
                                            Seleccionar
                                        </button>
                                        <!---->
                                    </td>
                                    <td rowspan="2">
                                        <button id="jugarPiropo" class="btn btn-primary">Jugar</button>
                                    </td>
                                    <td rowspan="2"></td>
                                    <td rowspan="2">
                                        <div id="historial_piropo">
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <button id="cerrar_piropo" class="btn btn-primary">Quitar</button>
                                    </td>
                                    <td>
                                        <div>
                                            <div id="WinElementsPiropo">
                                            </div>
                                            <div class="premios">
                                                <select id="premios_piropos" class="form-control">
                                                    <option>Premios</option>
                                                    <option value="50000">50.000 Gs En Saldo</option>
                                                </select
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="row" id="piropo2">
                <div class="col-xs-12">
                    <h3>Piropos 2</h3>
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th class="col-sm-1">Preview</th>
                                    <th class="col-sm-1">Modulo</th>
                                    <th class="col-sm-1">Ganador</th>
                                    <th class="col-sm-1">Jugar</th>
                                    <th class="col-sm-2">Acciones</th>
                                    <th class="col-sm-3">Historial</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td rowspan="3">
                                        <img class="juego_preview" src="/img/tvchat/interfaz/tvchat_piropo_preview.png">
                                    </td>
                                    <td>
                                        <button id="cargar_piropo2" class="btn btn-primary">Cargar</button>
                                    </td>
                                    <td>
                                        <button id="getWinElementsPiropo" class="btn btn-primary">
                                            Obtener
                                        </button>
                                    </td>
                                    <td rowspan="3">
                                        <button id="jugarPiropo2" class="btn btn-primary">Jugar</button>
                                    </td>
                                    <td>
                                        <div id="jugador_piropo2">
                                        </div>
                                    </td>
                                    </td>
                                    <td rowspan="3">
                                        <div id="historial_piropo2">
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <button id="cerrar_piropo" class="btn btn-primary">Quitar</button>
                                    </td>
                                    <td>
                                        <div>
                                            <div id="WinElementsPiropo2">
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <button id="jugarPiropo2Premio" type="button" class="btn btn-primary">C/ Premio</button>
                                    </td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td>
                                        <div class="premios">
                                            <select id="premios_piropos2" class="form-control">
                                                <option>Premios</option>
                                                <option value="50000">50.000 Gs En Saldo</option>
                                            </select
                                        </div>
                                    </td>
                                    <td>
                                        <button id="jugarPiropo2SinPremio" type="button" class="btn btn-primary">S/ Premio</button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <!--tragamonedas sexy-->
            <div class="row" id="tragamonedas_sexy">
                <div class="col-xs-12">
                    <h3>Tragamonedas Sexy</h3>
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th class="col-sm-1">Preview</th>
                                    <th class="col-sm-2">Ganador</th>
                                    <th class="col-sm-1">Modulo</th>
                                    <th class="col-sm-1">Jugar</th>
                                    <th class="col-sm-1">Acciones</th>
                                    <th class="col-sm-3">Historial</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td rowspan="4">
                                        <img class="juego_preview" src="/img/tvchat/interfaz/tvchat_tragamonedas_preview.png">
                                    </td>
                                    <td>
                                        <button id="getWinElementsTragamonedasSexy" type="button" class="btn btn-primary">Seleccionar</button>
                                    </td>
                                    <td rowspan="2">
                                        <button id="cargar_tragamonedas_sexy" class="btn btn-primary">Cargar</button>
                                    </td>
                                    <td rowspan="4">
                                        <button id="jugarTragamonedasSexy" class="btn btn-primary">Jugar</button>
                                    </td>
                                    <td>
                                        <button id="stopRouletteSexy1" class="btn btn-primary">Parar 1</button>
                                    </td>
                                    <td rowspan="4">
                                        <div id="historial_tragamonedas_sexy">
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td rowspan="3">
                                        <div id="WinElementsTragamonedasSexy"></div>
                                        <div id="selectWinElements" class="selectWinElements">
                                            <div class="stop_image_number_value param_label1">
                                                <span class="param_name">Tira 1: </span> <span class="stop_image_number_param1"></span>
                                            </div>
                                            <span id="image_sample1" class="image_sample1">
                                                <img data-value="0"  src="/img/tvchat/tragamonedas/zapato.png"/>
                                                <img data-value="1"  src="/img/tvchat/tragamonedas/bombacha.png"/>
                                                <img data-value="2"  src="/img/tvchat/tragamonedas/portacena.png"/>
                                            </span>
                                            <div class="stop_image_number_value param_label2">
                                                <span class="param_name">Tira 2: </span> <span class="stop_image_number_param2"></span>
                                            </div>
                                            <span id="image_sample2" class="image_sample2">
                                                <img data-value="0"  src="/img/tvchat/tragamonedas/zapato.png"/>
                                                <img data-value="1"  src="/img/tvchat/tragamonedas/bombacha.png"/>
                                                <img data-value="2"  src="/img/tvchat/tragamonedas/portacena.png"/>
                                            </span>
                                            <div class="stop_image_number_value param_label3">
                                                <span class="param_name">Tira 3: </span> <span class="stop_image_number_param3"></span>
                                            </div>
                                            <span id="image_sample3" class="image_sample3">
                                                <img data-value="0"  src="/img/tvchat/tragamonedas/zapato.png"/>
                                                <img data-value="1"  src="/img/tvchat/tragamonedas/bombacha.png"/>
                                                <img data-value="2"  src="/img/tvchat/tragamonedas/portacena.png"/>
                                            </span>
                                        </div>
                                        <div class="premios">
                                            <select id="premios_tragamonedas_sexy" class="form-control">
                                                <option>Premios</option>
                                                <option value="50000">50.000 Gs En Saldo</option>
                                            </select
                                        </div>
                                    </td>
                                    <td>
                                        <button id="stopRouletteSexy2" class="btn btn-primary">Parar 2</button>
                                    </td>
                                </tr>
                                <tr>
                                    <td rowspan="2">
                                        <button id="cerrar_tragamonedas_sexy" class="btn btn-primary">Quitar</button>
                                    </td>
                                    <td>
                                        <button id="stopRouletteSexy3" class="btn btn-primary">Parar 3</button>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <button id="mostrarGanadorTragamonedasSexy" class="btn btn-primary">Mostrar</button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <!--video-->
            <div class="row" id="video">
                <div class="col-xs-12">
                    <h3>Video</h3>
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th class="col-sm-1">Preview</th>
                                    <th class="col-sm-1">Modulo</th>
                                    <th class="col-sm-2">Ganador</th>
                                    <th class="col-sm-1">Jugar</th>
                                    <th class="col-sm-1">Acciones</th>
                                    <th class="col-sm-3">Historial</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td rowspan="2">
                                        Preview no disponible
                                    </td>
                                    <td>
                                        <button id="cargar_video" class="btn btn-primary">Cargar</button>
                                    </td>
                                    <td></td>
                                    <td rowspan="2"></td>
                                    <td rowspan="2"></td>
                                    <td rowspan="2"></td>
                                </tr>
                                <tr>
                                    <td>
                                        <button id="cerrar_video" class="btn btn-primary">Quitar</button>
                                    </td>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->

        <div class="modal fade" id="opciones_mensajes" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div style="width: 1300px" class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="myModalLabel">Seleccione el Mensaje</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <table class="table table-striped table-bordered table-hover table-heading no-border-bottom">
                                <thead>
                                <tr>
                                    <th>Mensaje</th>
                                    <th>Accion</th>
                                </tr>
                                </thead>
                                <tbody id="mensajes">
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- .Modal -->

        <!-- jQuery Version 1.11.0 -->
        <script src="/js/plugins/jquery-1.7.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="/js/plugins/bootstrap.min.js"></script>

        <!-- Morris Charts JavaScript -->
        <script src="/js/plugins/raphael.min.js"></script>
        <script src="/js/tvchat/tvchat.manager.js"></script>

    </body>

</html>
