<div class="tvchat_screen">
    <!--<div id="margenes" class="margenes"></div>-->
    <div class="marquee_habilitado">
    </div>
    <div class="tvchat">
        <div id="scroller">
            <div class="static-text">
                <div class="tvchat_logo">
                    <img src="/img/tvchat/tvchat_titulo_mensajero.png">
                </div>
                <div class="tvchat_logo_detalle_derecha">
                    <img src="/img/tvchat/tvchat_detalle_derecha.png">
                </div>
            </div>
            <div id="ventana" class="marquee"></div>
        </div>
    </div>
    <div class="costo">
        Costo por cada mensaje cobro semanal Gs. 2200 IVA incluido - Proveedor y Licenciatario Entermovil SA Asuncion Paraguay
    </div>
</div>
