<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8">
    <meta name="description" content="description">
    <meta name="author" content="FO">
    <meta name="keyword" content="keywords">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <script type="text/javascript" src="/js/plugins/jquery-1.7.js"></script>
    <link href="/css/plugins/bootstrap/bootstrap.css" rel="stylesheet">
    <link href="/css/chatcenter/signin.css" rel="stylesheet">
    <link href="/css/chatcenter/chat.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <style>
        body{
            padding-left: 10%;
            padding-right: 10%;
        }
        .fill {
            min-height: 100%;
        }
    </style>
    <title>Chat Entermovil</title>

    <script type="text/javascript">

        var ultimo_id = <?php echo $this->ultimo_id ?>;

        function verificarNuevosMensajes() {

            $.get("/tvchat/chat-nuevos-mensajes/ultimo/"+ultimo_id, null, function(respuesta) {
                if(respuesta.hayNuevosMensajes) {
                    //alert('Nuevos Mensajes');
                    ultimo_id = respuesta.ultimoId;
                    //$("#bloqueMensajes").scrollTop($("#bloqueMensajes")[0].scrollHeight);
                    location.reload();
                }
            }, "json");
        }

        $(document).ready(function() {

            //
            $('html, body').animate({
                scrollTop: $("#botonEnviar").offset().top
            }, 1500);

            $("#bloqueMensajes").scrollTop($("#bloqueMensajes")[0].scrollHeight);

            setInterval( verificarNuevosMensajes, 1000*10 );

        });

    </script>
</head>
<body>
    <div class="container-fluid fill" id="contenedorMensajes">
        <div class="panel panel-default" id="panelMensajes">
            <div class="panel-heading">
                <h3 class="panel-title">Usuario: <?php echo isset($this->cel)?$this->cel:''?></h3>
            </div>
            <div class="panel-body">

                <div class="row">

                    <div class="message-wrap col-lg-12">
                        <div class="msg-wrap" id="bloqueMensajes">

                            <?php if( !empty($this->datos_mostrar) ):?>

                                <?php $mensaje_hoy_mostrado = false; ?>
                                <?php foreach ( $this->datos_mostrar as $indice => $fila ): ?>

                                    <?php

                                    $fh_usuario = substr($fila['fh_mensaje_usuario'],0,10);
                                    $hora_usuario = substr($fila['fh_mensaje_usuario'],11,8);
                                    $hoy = ($fh_usuario == date('Y-m-d'));

                                    $fh_operador = substr($fila['fh_mensaje_operador'],0,10);
                                    $hora_operador = substr($fila['fh_mensaje_operador'],11,8);

                                    ?>

                                    <?php if($hoy && !$mensaje_hoy_mostrado): ?>
                                        <div class="alert alert-info msg-date">
                                            <strong>Hoy</strong>
                                        </div>
                                        <?php $mensaje_hoy_mostrado = true; ?>
                                    <?php endif; ?>

                                    <div class="media msg ">

                                        <div class="media-body">
                                            <small class="pull-left time"><i class="fa fa-clock-o"><?php echo ($hoy ? $hora_usuario : substr($fila['fh_mensaje_usuario'],0,19)) ?></i></small>

                                            <small class="pull-left col-lg-12"><?php echo $fila['mensaje_usuario']?></small>
                                        </div>

                                    </div>

                                    <div class="media msg ">

                                        <div class="media-body">

                                            <?php if(!empty( $fila['mensaje_operador'])): ?>
                                                <small class="pull-right time"><i class="fa fa-clock-o"><?php echo ($hoy ? $hora_operador: substr($fila['fh_mensaje_operador'],0,19)) ?></i></small>
                                                <small class="pull-right col-lg-12" style="text-align: right; color: cornflowerblue;"><?php echo $fila['mensaje_operador']?></small>
                                            <?php else: ?>
                                                <small class="pull-right time"><i class="fa fa-clock-o" style="color: cornflowerblue;">Esperando respuesta...</i></small>
                                            <?php endif; ?>
                                        </div>

                                    </div>

                                <?php endforeach; ?>

                            <?php else: ?>

                                <div class="alert alert-info msg-date">
                                    <strong>No hay mensajes</strong>
                                </div>

                            <?php endif?>

                        </div>

                        <form name="form1" method="post" action="/tvchat/chat-historial">

                            <input type="hidden" name="cel" value="<?php echo $this->cel ?>"/>

                            <div class="send-wrap ">
                                <input type="text" class="form-control send-message" placeholder="Escribir mensaje..." name="mensaje" id="mensaje"/>

                            </div>
                            <div class="btn-panel">
                                <input type="submit" class="btn btn-primary col-lg-4 text-right btn send-message-btn pull-right fa fa-plus" role="button" value="Enviar Mensaje" id="botonEnviar"/>
                            </div>

                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
</body>
