<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8">
    <meta name="description" content="description">
    <meta name="author" content="FO">
    <meta name="keyword" content="keywords">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link href="/css/plugins/bootstrap/bootstrap.css" rel="stylesheet">
    <link href="/css/chatcenter/signin.css" rel="stylesheet">
    <style>
        body{
            padding-left: 10%;
            padding-right: 10%;
        }
    </style>
    <title>Chat Entermovil</title>
</head>
<body>
    <div class="container">
        <form class="form-signin" role="form" name="form1" method="post" action ="/tvchat/chat-numero">
            <h2 class="form-signin-heading">Chat Entermovil</h2>
            <input class="form-control" type="tel" autofocus="" required="" placeholder="Número de Celular" id="cel" name="cel" value="<?php echo isset($this->cel)?$this->cel:''?>">
            <button class="btn btn-lg btn-primary btn-block" type="submit">Iniciar Chat</button>
        </form>
    </div>
</body>
