<!DOCTYPE html>
<html>
    <head>
        <title>TVChat Demo 800x600</title>
        <script type="text/javascript" src="/js/jquery-1.7.min.js"></script>
        <script type="text/javascript" src="/js/jquery.marquee.min.js"></script>
        <script type="text/javascript" src="/js/jquery.marquee.js"></script>
        <!--Tombola JS-->
        <script type="text/javascript" src="/js/tvchat.utils.js"></script>
        <script type="text/javascript" src="/js/tvchat.wheel.js"></script>
        <!--Master JS-->
        <script type="text/javascript" src="/js/tvchat.child.js"></script>
        <!--Tvchat CSS-->
        <link href="/css/tvchat.css" type="text/css" rel="stylesheet">
    </head>
    <body>
        <div class="tvchat_screen">
            <div class="titulo">
                <div class="jugar_izquierda">
<!--                    <img src="/img/LogoJugarIzquierdaAnimado.gif">-->
                    <img src="/img/chat_izquierda.gif">
                </div>
                <div class="logo_afortunado">
                    <img src="/img/LogoAfortunadoAnimado.gif">
                </div>
                <div class="jugar_derecha">
<!--                    <img src="/img/LogoJugarDerechaAnimado.gif">-->
                    <img src="/img/chat_derecha.gif">
                </div>
            </div>
            <div class="interactive">
                <div class="juegos">
                    <div id="game_wrapper">

                        <!--quitar despues-->
                        <div class="tragamonedas_wrapper">
                            <div id="tragamonedas_luces_verticales_izq" class="tragamonedas_luces_verticales_izq"></div>
                            <div id="tragamonedas_luces_verticales_der" class="tragamonedas_luces_verticales_der"></div>
                            <div id="tragamonedas_titulo" class="tragamonedas_titulo">
                                <img src="/img/tragamonedas_titulo.gif">
                            </div>
                            <div class="tragamonedas_tiras">
                                <div id="tragamonedas_luces_horizontales_arriba" class="tragamonedas_luces_horizontales_arriba"></div>
                                <div id="tragamonedas_luces_horizontales_abajo" class="tragamonedas_luces_horizontales_abajo"></div>
                                <div class="tira1">
                                    <div id="tira_imagenes1" class="roulette" style="display:none;">
                                    </div
                                </div>
                                <div class="tira2">
                                    <div id="tira_imagenes2" class="roulette1" style="display:none;">
                                    </div>
                                </div>
                                <div class="tira3">
                                    <div id="tira_imagenes3" class="roulette2" style="display:none;">
                                    </div>
                                </div>
                            </div>
                            <div class="tragamonedas_numeros_ganadores">
                                <div class="linea_ganadora">
                                    <div class="container_ganador">
                                        <div class="premio">Premio: Saldo para tu celular</div>
                                        <div class="linea">Ganador: 0982-3132XX</div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="conductora"></div>
            </div>
            <div class="tvchat">
                <div id="scroller">
                    <div class="static-text">
                        <div class="tvchat_logo">
                            <img src="/img/tvchat_logo.png">
                        </div>
                        <div class="tvchat_logo_detalle_derecha">
                            <img src="/img/tvchat_detalle_derecha.png">
                        </div>
                    </div>
                    <div id="ventana" class="marquee">Saludos desde Bella Vista Norte/// Besos a mi hermana desde Espanha</div>
                </div>
            </div>
            <div class="costo">
                Costo por cada mensaje cobro semanal Gs. 2200 IVA incluido - Proveedor y Licenciatario Entermovil SA Asuncion Paraguay
            </div>
        </div>
    </body>
</html>
