<div class="container-fluid">
    <div id="page-login" class="row">
        <div class="col-xs-12 col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
            <div class="box">
                <div class="box-content">
                    <div class="text-center">
                        <h3 class="page-header">Tvchat Login Page</h3>
                    </div>
                    <form class="form-signin" name = "form1" method="post" action ="/tvchat/login">
                        <div class="form-group">
                            <label class="control-label">Username</label>
                            <input type="text" name="login_user" id="login_user" class="form-control" name="username" autofocus/>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Password</label>
                            <input type="password" name="login_pass" id="login_pass" class="form-control" name="password" autofocus/>
                        </div>
                        <div class="text-center">
                            <button class="btn btn-primary" type="submit">Acceder</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

