<div class="tvchat_screen">
    <div class="titulo">
        <div class="jugar_izquierda">
            <img src="/img/tvchat/tvchat_jugar.gif">
        </div>
        <div class="logo_afortunado">
            <img src="/img/tvchat/tvchat_logo_afortunado.gif">
        </div>
        <div class="jugar_derecha">
            <img src="/img/tvchat/tvchat_jugar.gif">
        </div>
    </div>
    <div class="interactive">
        <div class="juegos">
            <div id="game_wrapper">
                <div id="mensaje_wrapper" class="mensaje_wrapper">
                    <h1 style="text-align: center">Piropo Seleccionado</h1>
                    <div id="mensaje_seleccionado">
                        <h3 style="text-align: center">Carajo</h3>
                    </div>
                </div>
            </div>
        </div>
        <div class="conductora"></div>
    </div>
    <div class="tvchat">
        <div id="scroller">
            <div class="static-text">
                <div class="tvchat_logo">
                    <img src="/img/tvchat/tvchat_titulo_mensajero.png">
                </div>
                <div class="tvchat_logo_detalle_derecha">
                    <img src="/img/tvchat/tvchat_detalle_derecha.png">
                </div>
            </div>
            <div id="ventana" class="marquee">Saludos desde Bella Vista Norte/// Besos a mi hermana desde Espanha</div>
        </div>
    </div>
    <div class="costo">
        Costo por cada mensaje cobro semanal Gs. 2200 IVA incluido - Proveedor y Licenciatario Entermovil SA Asuncion Paraguay
    </div>
</div>
