<div id="tvhot_mensajero" class="tvhot_mensajero" xmlns="http://www.w3.org/1999/html">
    <div class="marquee ver">
        <p>jQuery marquee is the best marquee plugin in the world</p>
        <p>OK NO</p>
        <p>OTRO MENSAJE</p>
        <p>NUEVO</p>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('.marquee').marquee({
            //speed in milliseconds of the marquee
            duration: 10000,
            //gap in pixels between the tickers
            gap: 0,
            //'left' or 'right'
            direction: 'up',
            pauseOnHover: false
        });
    })
</script>