<div xmlns="http://www.w3.org/1999/html">
    <div class="row">
        <div style="width: 592px; height: 370px; float:left">
            <h1>Proyectos en Ejecucion</h1>
            <p>Generalmente existen dos clases de proyectos en el marco del tiempo, los primeros obedecen a los esquemas de contrataciones
            publicas definidos a partir de restricciones de inicio: fecha de inicio y duracion y otros son los que aplican para grandes
            proyectos industriales denominados paradas de planta cuyas restricciones son fecha inicio y fecha fin. Generalmente existen dos clases de proyectos en el marco del tiempo, los primeros obedecen a los esquemas de contrataciones
            publicas definidos a partir de restricciones de inicio: fecha de inicio y duracion y otros son los que aplican para grandes
            proyectos industriales denominados paradas de planta cuyas restricciones son fecha inicio y fecha fin.
            </p>
            <p>Generalmente existen dos clases de proyectos en el marco del tiempo, los primeros obedecen a los esquemas de contrataciones
            publicas definidos a partir de restricciones de inicio: fecha de inicio y duracion y otros son los que aplican para grandes
            proyectos industriales denominados paradas de planta cuyas restricciones son fecha inicio y fecha fin.
            </p>
        </div>
        <div style="width: 266px; height: 370px; float:right">
            <h1>Avisos</h1>
            <p>Generalmente existen dos clases de proyectos en el marco del tiempo, los primeros obedecen a los esquemas de contrataciones
            publicas definidos a partir de restricciones de inicio: fecha de inicio y duracion y otros son los que aplican para grandes
            proyectos industriales denominados paradas de planta cuyas restricciones son fecha inicio y fecha fin.
            </p>
        </div>
    </div>
</div>