<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="../../assets/ico/favicon.png">

        <title>ENTERMOVIL</title>

        <!-- Bootstrap core CSS -->
        <script src="http://www.entermovil.com.py/js/jquery-1.8.0.min.js"></script>
        <script src="http://www.entermovil.com.py/bootstrap-3.0.0/dist/js/bootstrap.js"></script>
        <link rel="stylesheet" href="http://www.entermovil.com.py/bootstrap-3.0.0/dist/css/bootstrap.css">
        <!--<link href="../../dist/css/bootstrap.css" rel="stylesheet">-->

        <!-- Custom styles for this template -->
        <link href="http://www.entermovil.com.py/bootstrap/css/signin.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="../../assets/js/html5shiv.js"></script>
        <script src="../../assets/js/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>

   <div class="container">

        <form class="form-signin" name = "form1" method="post" action ="/cargar/login">
            <h2 style="text-align: center" class="form-signin-heading">Entermovil - Wap</h2>
            <input type="text" name="login_user" id="login_user" class="form-control" placeholder="Usuario" autofocus>
            <input type="password" name="login_pass" id="login_pass" class="form-control" placeholder="Contraseña">
            <button class="btn btn-lg btn-primary btn-block" type="submit">Ingresar</button>
        </form>

    </div>

    </body>
</html>
