<!doctype html>
<head>
    <meta charset="utf-8">
<!--    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="shortcut icon" href="favicon.png" /-->
    <title>Hide and show a DIV demo</title>

    <script src="http://www.entermovil.com.py/js/jquery-1.8.0.min.js"></script>
    <script src="http://www.entermovil.com.py/bootstrap-3.0.0/dist/js/bootstrap.js"></script>
    <link rel="stylesheet" href="http://www.entermovil.com.py/bootstrap-3.0.0/dist/css/bootstrap.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>

</head>

<body>
    <!-- Button trigger modal -->
    <a data-toggle="modal" href="#myModal" class="btn btn-primary">Launch modal</a>

    <div class="modal" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Modal title</h4>
                </div>
                <div class="modal-body">
                    Content for the dialog / modal goes here.
                </div>
                <div class="modal-footer">
                    <a href="#" data-dismiss="modal" class="btn">Close</a>
                    <a href="#" class="btn btn-primary">Save changes</a>
                </div>
            </div>
        </div>
    </div>
    </body>
</html>