<?php
    echo $this->doctype();
    echo "\n";
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headTitle() ?>
        <?php echo "\n" ?>
        <?php echo $this->headLink() ?>
        <?php echo "\n" ?>
        <?php echo $this->headStyle() ?>
        <?php echo "\n" ?>
        <?php echo $this->headScript() ?>
        <?php echo "\n" ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" media="all" href="/css/plugins/bootstrap/bootstrap.css">
        <link rel="stylesheet" type="text/css" media="all" href="/css/comportamiento/comportamiento.css">
    </head>
    <body>
        <div class="contenedor">
            <div class="row">
                <div style="height: 100px"></div>
            </div>
            <!--<div class="login">
                <form class="form-signin" name="form1" method="post" action="/comportamiento/login">
                    <div class="form-group">
                        <label class="control-label">Username</label>
                        <input type="text" name="login_user" id="login_user" class="form-control" name="username" autofocus/>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Password</label>
                        <input type="password" name="login_pass" id="login_pass" class="form-control" name="password" autofocus/>
                    </div>
                    <div class="text-center">
                        <button class="btn btn-primary" type="submit">Acceder</button>
                    </div>
                </form>
            </div>-->
            <div class="row logo_contacto">
                <div class="logo"></div>
                <div class="contacto"></div>
            </div>
            <div class="row">
                <div class="panel-navegacion">
                    <a href="#"><img src="/img/comportamiento/home.png"></a>
                    <a href="#"><img src="/img/comportamiento/home.png"></a>
                    <a href="#"><img src="/img/comportamiento/home.png"></a>
                    <a href="#"><img src="/img/comportamiento/home.png"></a>
                    <a href="#"><img src="/img/comportamiento/home.png"></a>
                    <a href="#"><img src="/img/comportamiento/home.png"></a>
                </div>
            </div>
            <div class="row">
                <div class="banner-buscar">
                    <!--poner ak el input para buscar-->
                </div>
            </div>
            <div>
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>
