<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width, maximum-scale=1, user-scalable=no"/>
        <meta name="HandheldFriendly" content="true" />

    <!--    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.css" />
        <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
        <script src="http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.js"></script>-->

        <link rel="stylesheet" href="http://wwww.entermovil.com.py/jquerymobile/demos/css/themes/default/jquery.mobile-1.3.1.min.css" />
        <script src="http://wwww.entermovil.com.py/jquerymobile/demos/js/jquery.js"></script>
        <script src="http://wwww.entermovil.com.py/jquerymobile/demos/js/jquery.mobile-1.3.1.min.js"></script>

        <link rel="apple-touch-icon-precomposed" href="/apple-touch-icon.png" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />

        <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png" />
        <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png" />
        <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-144x144.png" />

        <link rel="apple-touch-startup-image" href="/startup.png">

        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />

        <title>TwitterSMS</title>

        <style type="text/css">

            .ui-page {
                background: orange;
            }

            #navegador ul{
                list-style-type: none;
                text-align: center;
            }
            #navegador li{
                display: inline;
                text-align: center;
                margin: 0 10px 0 0;
            }
            #navegador li a {
                padding: 2px 7px 2px 7px;
                color: #666;
                background-color: #eeeeee;
                border: 1px solid #ccc;
                text-decoration: none;
            }
            a{
                text-decoration: none;
            }
            #navegador li a:hover{
                background-color: #333333;
                color: #ffffff;
            }
            div{
                margin-left: auto;
                margin-right: auto;
                text-align: center;
            }
            #navegador{
                margin-left: auto;
                margin-right: auto;
            }
            #mensajes{
                margin-left: auto;
                margin-right: auto;
            }
        </style>
    </head>
    <body>
        <!--<div data-role="header" data-theme="b">
            <h1>NOTICIAS</h1>
        </div>-->
        <?php echo $this->layout()->content; ?>


    </body>
</html>