<?php
    echo $this->doctype();
    echo "\n";
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta charset="utf-8">
        <meta name="description" content="description">
        <meta name="author" content="DAAS">
        <meta name="keyword" content="keywords">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="/css/plugins/bootstrap/bootstrap.css" rel="stylesheet">
        <link href="/css/tvchat/style.css" rel="stylesheet">

        <?php echo $this->headTitle() ?>
        <?php echo "\n" ?>
        <?php echo $this->headLink() ?>
        <?php echo "\n" ?>
        <?php echo $this->headStyle() ?>
        <?php echo "\n" ?>
        <?php echo $this->headScript() ?>
        <?php echo "\n" ?>
    </head>
    <body>
        <!--Start Header-->
        <header class="navbar">
            <div class="container-fluid expanded-panel">
                <div class="row">
                    <div id="logo" class="col-xs-12 col-sm-2">
                        <a href="#">Entermovil SA</a>
                    </div>
                    <div id="top-panel" class="col-xs-12 col-sm-10">
                        <div class="row">
                            <div class="col-xs-8 col-sm-4">
                                <a href="#" class="show-sidebar">
                                    <i class="fa fa-bars"></i>
                                </a>
                            </div>
                            <div class="col-xs-4 col-sm-8 top-panel-right">
                                <ul class="nav navbar-nav pull-right panel-menu">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle account" data-toggle="dropdown">
                                            <i class="fa fa-angle-down pull-right"></i>
                                            <div class="user-mini pull-right">
                                                <span class="welcome">Welcome,</span>
                                                <span><?php echo $this->infoSesion()->usuario() ?></span>
                                            </div>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="#">
                                                    <i class="fa fa-user"></i>
                                                    <span class="hidden-sm text">Profile</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/tvchat/logout">
                                                    <i class="fa fa-power-off"></i>
                                                    <span class="hidden-sm text">Logout</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!--Start Breadcrumb-->
                        <div class="row">
                            <div id="breadcrumb" class="col-xs-12">
                                <ol class="breadcrumb">
                                    <li><a href="#">Dashboard</a></li>
                                    <button id="cerrar_ventana_principal" style="float: right" class="btn btn-danger">Cerrar Pantalla</button>
                                    <button id="abrir_ventana_principal" style="float: right" class="btn btn-danger">Abrir Pantalla</button>
                                    <button id="vaciar_localstorage" style="float: right" class="btn btn-danger">Vaciar</button>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!--End Header-->
        <!--Start Container-->
        <div id="main" class="container-fluid">
            <div class="row">
                <div id="sidebar-left" class="col-xs-2 col-sm-2">
                    <ul class="nav main-menu">
                        <li>
                            <div>
                                <table class="table table-striped table-bordered table-hover table-heading">
                                    <thead>
                                        <tr>
                                            <th colspan="2" class="col-sm-1">Totales</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td style="background-color: #ffffff" class="col-sm-1">Total Guaranies: </td>
                                            <td style="background-color: #ffffff" class="col-sm-1" id="total_guaranies">0</td>
                                        </tr>
                                        <tr>
                                            <td style="background-color: #ffffff">Total Sorteos: </td>
                                            <td style="background-color: #ffffff" id="total_sorteos">0</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </li>
                    </ul>
                </div>
                <!--Start Content-->
                <div id="content" class="col-xs-12 col-sm-10">
                    <div class="contenedor">
                        <?php echo $this->layout()->content; ?>
                    </div>
                </div>
                <!--End Content-->
            </div>
        </div>
    </body>
</html>
