<?php
    echo $this->doctype();
    echo "\n";
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta charset="utf-8">
        <meta name="description" content="description">
        <meta name="author" content="DAAS">
        <meta name="keyword" content="keywords">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="/css/tvchat/tvchat.css" rel="stylesheet">

        <?php echo $this->headTitle() ?>
        <?php echo "\n" ?>
        <?php echo $this->headLink() ?>
        <?php echo "\n" ?>
        <?php echo $this->headStyle() ?>
        <?php echo "\n" ?>
        <?php echo $this->headScript() ?>
        <?php echo "\n" ?>
    </head>
    <body>
        <!--Start Content-->
        <div id="content" class="col-xs-12 col-sm-10">
            <div class="contenedor">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
        <!--End Content-->
    </body>
</html>
