<div style="width: <?php echo $this->ua['ancho_tabla'] .'px'?>; background: #ffffff">

    <table id="navegador" align="center" width="<?php echo $this->ua['ancho_tabla'] . 'px'?>" cellspacing="0" cellpadding="0" border="0">
        <tr>
            <td><img class="menu" src="/<?php echo $this->ua['borde_arriba'] ?>" alt="NAVEGADOR" /></td>
        </tr>
    </table>
    <table id="tabla_suscripcion" width="<?php echo $this->ua['ancho_tabla'] . 'px'?>" border="0" cellspacing="2" cellpadding="5" align="center" bgcolor = "white">

        <tr>
            <td valign="center"><h1 style="color: black; text-align: center; padding: 0;">Acceso Restringido</h1></td>
        </tr>
        <tr style="line-height: 100%">
            <td valign="center">
                <h3 style="color: black; text-align: center; margin: 0;">Favor enviar PORTAL al 35500 para suscribirse</h3>
            </td>
        </tr>
    </table>
    <table id="borde_abajo" align="center" width="<?php echo $this->ua['ancho_tabla'] . 'px'?>" cellspacing="0" cellpadding="0" border="0">
        <tr>
            <td><img class="menu" src="/<?php echo $this->ua['borde_abajo'] ?>" alt="BORDE_ABAJO"></td>
        </tr>
    </table>
</div>

