<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <title>ENTERMOVIL</title>
    </head>
    <body>
        <center>
            <table width="<?php echo $this->ancho ?>" border="0" cellspacing="0" cellpadding="0" id="principal" align="center">

                <tr>
                    <td colspan="2"><a href="/test/03_1.mp4">archivo</a></td>
                </tr>

            </table>
        </center>
    </body>
</html>

