<div id="contenidos_imagenes" style="width: <?php echo $this->ua['ancho_tabla'] .'px'?>; background: #ffffff">

    <table id="navegador" align="center" width="<?php echo $this->ua['ancho_tabla'] . 'px'?>" cellspacing="0" cellpadding="0" border="0">

        <tr>
            <td><img class="menu" src="/<?php echo $this->ua['navigator_layer1'] ?>" alt="NAVEGADOR" /></td>
            <td><a class="menu" href="/wap/categorias"><img class="menu" src="/<?php echo $this->ua['navigator_layer2'] ?>" alt="NAVEGADOR_HOME" /></a></td>
            <td><a class="menu" href="/wap/videos"><img class="menu" src="/<?php echo $this->ua['navigator_layer3'] ?>" alt="NAVEGADOR_VIDEOS" /></a></td>
            <td><a class="menu" href="/wap/imagenes"><img class="menu" src="/<?php echo $this->ua['navigator_layer4_v'] ?>" alt="NAVEGADOR_IMAGENES" /></a></td>
            <td><a class="menu" href="/wap/audios"><img class="menu" src="/<?php echo $this->ua['navigator_layer5'] ?>" alt="NAVEGADOR_AUDIOS" /></a></td>
            <td><img class="menu" src="/<?php echo $this->ua['navigator_layer6'] ?>" alt="NAVEGADOR"/></td>
        </tr>
        <tr style="height: 2px"></tr>
    </table>

    <?php if($this->ua['ancho'] >= 240){ ?>

        <table width="<?php echo $this->ua['ancho_tabla'] . 'px'?>" border="0" cellspacing="0" cellpadding="1" id="principal" align="center" bgcolor="white">

            <?php foreach ( $this->contenidos as $id_categoria=>$subcategorias ):?>

                <tr style="height: 5px"></tr>
                <tr style="height: 30px">
                    <td style="width:<?php echo $this->ua['ancho_costado']?>px;"></td>

                    <td id="titulo" bgcolor = "#9acd32" colspan="3" align="center"><font color="black" face="arial" size="1">Fondos</font></td>

                    <td style="width:<?php echo $this->ua['ancho_costado']?>px;"></td>
                </tr>
                <tr style="height: 5px"></tr>
                <tr>
                    <td style="width:<?php echo $this->ua['ancho_costado']?>px;"></td>
                    <td><font color="black" face="arial" size="2">Sigla: </font></td>
                    <td><font color="red" face="arial" size="2"><?php echo $this->sigla_tipeada?></font></td>
                    <td></td>
                    <td style="width:<?php echo $this->ua['ancho_costado']?>px;"></td>
                </tr>
                <?php if( isset( $subcategorias['hijos'] ) ){ ?>

                    <?php foreach($subcategorias['hijos'] as $tercernivel):?>

                        <?php if(isset($tercernivel['preview'])){ ?>

                            <tr>
                                <td style="width:<?php echo $this->ua['ancho_costado']?>px;"></td>

                                <?php foreach( $tercernivel['preview'] as $indice=>$imagen ):?>
                                    <?php if( $imagen['id_categoria'] == '39' ){ ?>
                                        <td>

                                            <a href="/wap/siglas/id-p/<?php echo $imagen['id_promocion']?>/id-c/<?php echo $imagen['id_categoria']?>/id/<?php echo $imagen['id_contenido']?>/iniciales/<?php echo $this->sigla_tipeada?>"><img src="<?php echo $imagen['path']?>"></a>

                                        </td>
                                    <?php } ?>
                                <?php endforeach;?>

                                <td style="width:<?php echo $this->ua['ancho_costado']?>px;"></td>
                            </tr>
<!--                            <tr>
                                <td style="width:<?php /*echo $this->ua['ancho_costado']*/?>px;"></td>
                                <?php /*foreach( $tercernivel['preview'] as $indice=>$imagen ):*/?>
                                    <?php /*if( $imagen['id_categoria'] == '39' ){ */?>
                                        <td><a href="/wap/siglas/id-p/<?php /*echo $imagen['id_promocion']*/?>/id-c/<?php /*echo $imagen['id_categoria']*/?>/id/<?php /*echo $imagen['id_contenido']*/?>/iniciales/<?php /*echo $this->sigla_tipeada*/?>"><input type="button" size= "3" value="OK"></a></td>
                                    <?php /*} */?>
                                <?php /*endforeach;*/?>
                                <td style="width:<?php /*echo $this->ua['ancho_costado']*/?>px;"></td>
                            </tr>-->

                            <?php /*break; */?>
                        <?php }else{ ?>
                            <tr>
                                <td style="width:<?php echo $this->ua['ancho_costado']?>px;"></td>
                                <td class="subtitulo" bgcolor = "#9acd32" colspan="3" align="left"><font color="blue" face="arial" size="1"><?php echo $tercernivel['nombre_categoria']?></font></td>
                                <td style="width:<?php echo $this->ua['ancho_costado']?>px;"></td>
                            </tr>
                            <tr>
                                <td style="width:<?php echo $this->ua['ancho_costado']?>px;"></td>
                                <td colspan="3"><font color="red" face="arial" size="1">No existen contenidos</font></td>
                                <td style="width:<?php echo $this->ua['ancho_costado']?>px;"></td>
                            </tr>
                        <?php } ?>
                        <tr style="height: 5px"></tr>

                    <?php endforeach;?>
                <?php }else{ ?>
                    <tr>
                        <td style="width:<?php echo $this->ua['ancho_costado']?>px;"></td>
                        <td colspan="3"><font color="red" face="arial" size="1">No existen contenidos</font></td>
                        <td style="width:<?php echo $this->ua['ancho_costado']?>px;"></td>
                    </tr>

                <?php } ?>

            <?php endforeach;?>
            <tr style="height: 10px">

            </tr>
        </table>

    <?php }?>

    <table id="borde_abajo" align="center" width="<?php echo $this->ua['ancho_tabla'] . 'px'?>" cellspacing="0" cellpadding="0" border="0">
        <tr>
            <td><img class="menu" src="/<?php echo $this->ua['borde_abajo'] ?>" alt="BORDE_ABAJO"></td>
        </tr>
    </table>
</div>