
<div id="bloque_mes">
    Mes Seleccionado:&nbsp;
    <select id="mes" name="mes">
        <?php foreach($this->rango_seleccion as $rango): ?>
        <option value="<?php echo $rango['anho'].'-'.($rango['mes']<10? '0'.$rango['mes'] : $rango['mes']) ?>"<?php echo ($rango['selected'] == 'selected' ? ' selected="selected"' : '') ?>><?php echo $rango['descripcion'] ?></option>
        <?php endforeach; ?>
    </select>
</div>

<div id="bloque_instructivo">
    <!--<h3>Referencias de Cobros</h3>
    <p>Precio Público = Gs. 2.000 sin IVA por cada contenido cobrado y entregado</p>
    <p>25% Enter Movil = Gs. 500</p>
    <p>75% Otros = Gs. 1.500 (Teléfonica = 70% / Licenciatario 5%)</p>-->
    <p><span style="width: 30px; background-color: #79eb74; display: block; float: left;">&nbsp;</span>&nbsp;= Día de Envío</p>
    <p><span style="width: 30px; background-color: #fff835; display: block; float: left;">&nbsp;</span>&nbsp;= Día Actual</p>
    <p>Ubicación de Productos de mayor a menor según cantidad de suscriptos</p>
</div>

<?php foreach($this->numeros as $numero): ?>
<table id="tabla_numero_<?php echo $numero ?>" class="tabla_reporte">
    <thead>
        <tr>
            <th class="celda_vacia"></th>
            <th colspan="4" class="borde_arriba borde_derecha" style="height: 25px; border-bottom: none;">Mes: <?php echo $this->nombre_mes ?> / Año: <?php echo $this->anho ?></th>
            <th colspan="<?php echo (3 + $this->cantidad_dias) ?>" class="celda_vacia"></th><!-- cantidad dias + 2 columnas -->
        </tr>
        <tr>
            <th class="fondo_naranja borde_arriba" style="min-width: 50px; width: 50px;"><?php echo $numero ?></th>
            <th colspan="4" class="fondo_naranja borde_arriba">Detalles Cobros</th>

            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <th class="nro_dia borde_arriba<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>" title="<?php echo $this->nombres_dias_del_mes[$i]['nombre_dia'] ?>"><?php echo $i ?></th>
            <?php endfor; ?>

            <th class="fondo_naranja totales borde_arriba">Totales</th>
            <th class="fondo_naranja totales borde_arriba">Carrier</th>
            <th class="fondo_naranja porcentaje borde_arriba">% Liquidacion</th>
        </tr>

    </thead>
    <tfoot>

        <tr class="celda_separador">
            <td class="celda_vacia"></td>
            <td colspan="<?php echo (3 + $this->cantidad_dias + 2) ?>" class="separador">&nbsp;</td>
        </tr>

        <tr>
            <th class="celda_vacia"></th>
            <th rowspan="3">Totales</th>
            <th rowspan="3">TOTAL</th>
            <th rowspan="3"><?php echo $this->numero($this->datos[$numero]['cobros_x_mes']['TOTALES_MES']['TOTAL']['total_suscriptos']) ?></th>
            <th class="descripcion_cobro">Cobros</th>

            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <th class="numero<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero($this->datos[$numero]['cobros_x_mes']['TOTALES_MES']['TOTAL']['datos_cobros'][$i]['total_cobros']) ?>&nbsp;</th>
            <?php endfor; ?>

            <th class="numero borde_derecha celda_total"><?php echo $this->numero($this->datos[$numero]['cobros_x_mes']['TOTALES_MES']['TOTAL']['total_cobros']) ?>&nbsp;</th>

            <th class="celda_vacia"></th>
        </tr>
        <tr>
            <th class="celda_vacia"></th>
            <th class="descripcion_cobro celda_cliente">ENTER</th>

            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <th class="numero celda_cliente"><?php echo $this->numero($this->datos[$numero]['cobros_x_mes']['TOTALES_MES']['TOTAL']['datos_cobros'][$i]['total_bruto_cliente']) ?>&nbsp;</th>
            <?php endfor; ?>

            <th class="numero celda_cliente borde_derecha celda_total"><?php echo $this->numero($this->datos[$numero]['cobros_x_mes']['TOTALES_MES']['TOTAL']['total_bruto_cliente']) ?>&nbsp;</th>

            <th class="celda_vacia"></th>
        </tr>
        <tr>
            <th class="celda_vacia"></th>
            <th class="descripcion_cobro">OTROS</th>

            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <th class="numero<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero($this->datos[$numero]['cobros_x_mes']['TOTALES_MES']['TOTAL']['datos_cobros'][$i]['total_bruto_otros']) ?>&nbsp;</th>
            <?php endfor; ?>

            <th class="numero borde_derecha celda_total"><?php echo $this->numero($this->datos[$numero]['cobros_x_mes']['TOTALES_MES']['TOTAL']['total_bruto_otros']) ?>&nbsp;</th>

            <th class="celda_vacia"></th>
        </tr>

    </tfoot>

    <tbody>

        <?php
            $promo_actual = '';
            $usar_separador_arriba = false;
            $usar_separador_abajo = false;
        ?>
        <?php foreach($this->datos[$numero]['promociones'] as $promocion): ?>
        <?php
            if($promo_actual == '') {
                //no se usa separador
                $usar_separador_arriba = false;

            } else {
                $estilo_separador = 'separador';
                if($promo_actual == $promocion['alias']) {
                    $estilo_separador = 'separador_misma_promocion';
                    $usar_separador_arriba = true;

                } else {
                    $estilo_separador = 'separador';
                    $usar_separador_arriba = true;
                }

            }
            $promo_actual = $promocion['alias'];

        ?>

            <?php if($usar_separador_arriba): ?>
            <tr class="celda_separador">
                <td class="celda_vacia"></td>
                <td colspan="<?php echo (3 + $this->cantidad_dias + 2) ?>" class="<?php echo $estilo_separador ?>">&nbsp;</td>
            </tr>
            <?php endif; ?>

            <tr>
                <td rowspan="3" class="celda_vacia"></td>
                <td rowspan="3" class="alias"><?php echo $promocion['alias'] ?></td>

                <td rowspan="3" class="carrier<?php echo ' ' . strtolower($this->carriers[$promocion['id_carrier']]) ?>"><?php echo $this->carriers[$promocion['id_carrier']] ?></td>

                <td rowspan="3" class="suscriptos"><?php echo $this->numero($this->datos[$numero]['cobros_x_mes'][$promocion['alias']][$promocion['id_carrier']]['total_suscriptos']) ?></td>
                <td class="descripcion_cobro">Cobros</td>

                <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
                <td class="numero<?php echo (in_array($this->nombres_dias_del_mes[$i]['dia_semana'], $this->datos[$numero]['calendario_envios'][$promocion['id_promocion']][$promocion['id_carrier']]) ? ' dia_envio' : '') ?><?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero($this->datos[$numero]['cobros_x_mes'][$promocion['alias']][$promocion['id_carrier']]['datos_cobros'][$i]['total_cobros']) ?>&nbsp;</td>
                <?php endfor; ?>

                <td class="numero celda_total"><?php echo $this->numero($this->datos[$numero]['cobros_x_mes'][$promocion['alias']][$promocion['id_carrier']]['total_cobros']) ?>&nbsp;</td>
                <td rowspan="3" class="numero celda_total"><?php echo $this->carriers[$promocion['id_carrier']] ?></td>
                <td rowspan="3" class="numero_porcentaje" title="<?php echo $promocion['alias'] ?>"><?php echo ($this->datos[$numero]['cobros_x_mes']['TOTALES_MES']['TOTAL']['total_cobros'] > 0 ? $this->porcentaje($this->datos[$numero]['cobros_x_mes'][$promocion['alias']][$promocion['id_carrier']]['total_cobros'] / $this->datos[$numero]['cobros_x_mes']['TOTALES_MES']['TOTAL']['total_cobros']) : 0) ?><br /><span style="font-size: 10px;"><?php echo $promocion['alias'] ?></span></td>
            </tr>

            <tr>
                <td class="descripcion_cobro celda_cliente">ENTER <?php echo $this->costos_x_promocion[$promocion['id_promocion']][$promocion['id_carrier']]['monto_entermovil'] ?>gs.</td>

                <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
                <td class="monto_gs celda_cliente"><?php echo $this->numero($this->datos[$numero]['cobros_x_mes'][$promocion['alias']][$promocion['id_carrier']]['datos_cobros'][$i]['total_bruto_cliente']) ?></td>
                <?php endfor; ?>

                <td class="monto_gs celda_cliente celda_total"><?php echo $this->numero($this->datos[$numero]['cobros_x_mes'][$promocion['alias']][$promocion['id_carrier']]['total_bruto_cliente']) ?>&nbsp;</td>

            </tr>
            <tr>
                <td class="descripcion_cobro">Otros <?php echo $this->costos_x_promocion[$promocion['id_promocion']][$promocion['id_carrier']]['monto_otros'] ?>gs.</td>

                <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
                <td class="monto_gs<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero($this->datos[$numero]['cobros_x_mes'][$promocion['alias']][$promocion['id_carrier']]['datos_cobros'][$i]['total_bruto_otros']) ?></td>
                <?php endfor; ?>

                <td class="monto_gs celda_total"><?php echo $this->numero($this->datos[$numero]['cobros_x_mes'][$promocion['alias']][$promocion['id_carrier']]['total_bruto_otros']) ?>&nbsp;</td>
            </tr>


        <?php endforeach; ?>

    </tbody>
</table>
<?php endforeach; ?>

<table id="tabla_totales_TOTAl" class="tabla_reporte">
    <thead>
    <tr>
        <th class="celda_vacia"></th>
        <th colspan="4" class="borde_arriba borde_derecha" style="height: 25px; border-bottom: none;">Mes: <?php echo $this->nombre_mes ?> / Año: <?php echo $this->anho ?></th>
        <th colspan="<?php echo (3 + $this->cantidad_dias) ?>" class="celda_vacia"></th><!-- cantidad dias + 2 columnas -->
    </tr>
    <tr>
        <th class="fondo_naranja borde_arriba" style="min-width: 50px; width: 50px;">TOTAL</th>
        <th colspan="4" class="fondo_naranja borde_arriba">Detalles Cobros</th>

        <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
        <th class="nro_dia borde_arriba<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>" title="<?php echo $this->nombres_dias_del_mes[$i]['nombre_dia'] ?>"><?php echo $i ?></th>
        <?php endfor; ?>

        <th class="fondo_naranja totales borde_arriba">Totales</th>
        <th class="fondo_naranja totales borde_arriba">Carrier</th>
        <th class="fondo_naranja porcentaje borde_arriba">% Liquidacion</th>
    </tr>

    </thead>
    <tfoot>
    <tr>
        <th class="celda_vacia"></th>
        <th rowspan="3" class="alias">Totales</th>
        <th rowspan="3" class="carrier">&nbsp;&nbsp;&nbsp;&nbsp;TOTAL</th>
        <th rowspan="3" class="suscriptos"><?php echo $this->numero($this->datos['TOTALES']['cobros_x_mes']['TOTALES_MES']['total_suscriptos']) ?></th>
        <th class="descripcion_cobro">Cobros</th>

        <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
        <th class="numero<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero($this->datos['TOTALES']['cobros_x_mes']['TOTALES_MES']['datos_cobros'][$i]['total_cobros']) ?>&nbsp;</th>
        <?php endfor; ?>

        <th class="numero borde_derecha celda_total"><?php echo $this->numero($this->datos['TOTALES']['cobros_x_mes']['TOTALES_MES']['total_cobros']) ?>&nbsp;</th>
        <td rowspan="3" class="carrier">&nbsp;&nbsp;&nbsp;&nbsp;TOTAL</td>

        <th class="celda_vacia"></th>
    </tr>
    <tr>
        <th class="celda_vacia"></th>
        <th class="descripcion_cobro celda_cliente">ENTER</th>

        <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
        <th class="numero celda_cliente"><?php echo $this->numero($this->datos['TOTALES']['cobros_x_mes']['TOTALES_MES']['datos_cobros'][$i]['total_bruto_cliente']) ?>&nbsp;</th>
        <?php endfor; ?>

        <th class="numero celda_cliente borde_derecha celda_total"><?php echo $this->numero($this->datos['TOTALES']['cobros_x_mes']['TOTALES_MES']['total_bruto_cliente']) ?>&nbsp;</th>

        <th class="celda_vacia"></th>
    </tr>
    <tr>
        <th class="celda_vacia"></th>
        <th class="descripcion_cobro">OTROS</th>

        <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
        <th class="numero<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero($this->datos['TOTALES']['cobros_x_mes']['TOTALES_MES']['datos_cobros'][$i]['total_bruto_otros']) ?>&nbsp;</th>
        <?php endfor; ?>

        <th class="numero borde_derecha celda_total"><?php echo $this->numero($this->datos['TOTALES']['cobros_x_mes']['TOTALES_MES']['total_bruto_otros']) ?>&nbsp;</th>


        <th class="celda_vacia"></th>
    </tr>
    </tfoot>
</table>