
<div id="bloque_mes">
    Servicio:&nbsp;
    <select name="id_promocion" id="id_promocion">
        <?php foreach($this->promociones as $promocion): ?>
        <option value="<?php echo $promocion['id_promocion'] ?>"<?php echo (isset($this->id_promocion_seleccionado) && $this->id_promocion_seleccionado == $promocion['id_promocion']) ? ' selected="selected"' : '' ?>><?php echo $promocion['promocion'] ?></option>
        <?php endforeach; ?>
    </select>&nbsp;&nbsp;
    Mes Seleccionado:&nbsp;
    <select id="mes" name="mes">
        <?php foreach($this->rango_seleccion as $rango): ?>
        <option value="<?php echo $rango['anho'].'-'.($rango['mes']<10? '0'.$rango['mes'] : $rango['mes']) ?>"<?php echo ($rango['selected'] == 'selected' ? ' selected="selected"' : '') ?>><?php echo $rango['descripcion'] ?></option>
        <?php endforeach; ?>
    </select>&nbsp;&nbsp;
    <input type="button" id="cargar_suscriptos" value="Cargar">
</div>

<?php if(isset($this->id_promocion_seleccionado)): ?>

<table id="tabla_suscriptos" class="tabla_reporte">
    <thead>
        <tr>
            <th class="celda_vacia"></th>
            <th colspan="4" class="borde_arriba borde_derecha" style="height: 25px; border-bottom: none;">Mes: <?php echo $this->nombre_mes ?> / Año: <?php echo $this->anho ?></th>
            <th colspan="15" class="celda_vacia"></th><!-- cantidad dias + 2 columnas -->
            <th colspan="4" class="borde_arriba borde_derecha" style="height: 25px; border-bottom: none;">Mes: <?php echo $this->nombre_mes ?> / Año: <?php echo $this->anho ?></th>
            <th colspan="<?php echo ($this->cantidad_dias-15) ?>" class="celda_vacia"></th><!-- cantidad dias + 2 columnas -->
            <th colspan="4" class="borde_arriba borde_derecha" style="height: 25px; border-bottom: none;">Mes: <?php echo $this->nombre_mes ?> / Año: <?php echo $this->anho ?></th>
        </tr>
        <tr>
            <th class="fondo_naranja borde_arriba" style="min-width: 50px; width: 50px;"><?php echo $this->promocion['numero'] ?></th>
            <th colspan="4" class="fondo_naranja borde_arriba"><?php echo $this->promocion['alias'] ?></th>

            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <th class="nro_dia borde_arriba<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>" title="<?php echo $this->nombres_dias_del_mes[$i]['nombre_dia'] ?>"><?php echo $i ?></th>
                <?php if($i==15): ?>
                <th colspan="4" class="fondo_naranja borde_arriba"><?php echo $this->promocion['numero'] ?>&nbsp;-&nbsp;<?php echo $this->promocion['alias'] ?></th>
                <?php endif; ?>
            <?php endfor; ?>

            <th colspan="4" class="fondo_naranja borde_arriba"><?php echo $this->promocion['alias'] ?></th>
            <th class="fondo_naranja totales borde_arriba borde_derecha">Totales</th>
        </tr>

    </thead>
    <tfoot>
        <?php
        $rowspan_hora = '';
        $cantidad_carriers = count($this->carriers_promocion);
        if($cantidad_carriers > 1) {
            $rowspan_hora = ' rowspan="'. ($cantidad_carriers*2) .'"';
        }
        $carriers_procesados = 0;

        ?>

        <tr>
            <th class="fondo_naranja" style="min-width: 50px; width: 50px;"><?php echo $this->promocion['numero'] ?></th>
            <th colspan="4" class="fondo_naranja"><?php echo $this->promocion['alias'] ?></th>

            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <th class="nro_dia<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>" title="<?php echo $this->nombres_dias_del_mes[$i]['nombre_dia'] ?>"><?php echo $i ?></th>
            <?php if($i==15): ?>
                <th colspan="4" class="fondo_naranja"><?php echo $this->promocion['numero'] ?>&nbsp;-&nbsp;<?php echo $this->promocion['alias'] ?></th>
                <?php endif; ?>
            <?php endfor; ?>

            <th colspan="4" class="fondo_naranja"><?php echo $this->promocion['alias'] ?></th>
            <th class="fondo_naranja totales borde_derecha">Totales</th>
        </tr>

        <?php foreach($this->carriers_promocion as $id_carrier): ?>
        <tr>
            <td class="celda_vacia"></td>
            <?php if($carriers_procesados == 0): ?>
            <th class="alias<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"<?php echo $rowspan_hora ?>>TOTALES</th>
            <?php endif; ?>
            <th rowspan="2" class="carrier<?php echo ' ' . strtolower($this->carriers[$id_carrier]) ?><?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo $this->carriers[$id_carrier] ?></th>
            <th class="numero celda_total suscriptos<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo isset($this->datos['TOTALES'][$id_carrier]['TOTAL_ALTA']) ? $this->datos['TOTALES'][$id_carrier]['TOTAL_ALTA'] : '' ?></th>
            <th class="descripcion_cobro<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>">Altas</th>
            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <th class="numero<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?><?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo (isset($this->datos['TOTALES'][$id_carrier]['datos'][$i]['ALTA']) ? $this->numero($this->datos['TOTALES'][$id_carrier]['datos'][$i]['ALTA']) : '')  ?>&nbsp;</th>
            <?php if($i==15): ?>
                <?php if($carriers_procesados == 0): ?>
                    <th class="alias"<?php echo $rowspan_hora ?>>TOTALES</th>
                    <?php endif; ?>
                <th rowspan="2" class="carrier<?php echo ' ' . strtolower($this->carriers[$id_carrier]) ?><?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo $this->carriers[$id_carrier] ?></th>
                <th class="numero celda_total suscriptos<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo isset($this->datos['TOTALES'][$id_carrier]['TOTAL_ALTA']) ? $this->datos['TOTALES'][$id_carrier]['TOTAL_ALTA'] : '' ?></th>
                <th class="descripcion_cobro<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>">Altas</th>
                <?php endif; ?>
            <?php endfor; ?>

            <?php if($carriers_procesados == 0): ?>
            <th class="alias"<?php echo $rowspan_hora ?>>TOTALES</th>
            <?php endif; ?>
            <th rowspan="2" class="carrier<?php echo ' ' . strtolower($this->carriers[$id_carrier]) ?><?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo $this->carriers[$id_carrier] ?></th>
            <th class="numero celda_total suscriptos<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo isset($this->datos['TOTALES'][$id_carrier]['TOTAL_ALTA']) ? $this->datos['TOTALES'][$id_carrier]['TOTAL_ALTA'] : '' ?></th>
            <th class="borde_derecha descripcion_cobro<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>">Altas</th>

        </tr>
        <tr>
            <td class="celda_vacia"></td>
            <td class="numero celda_total suscriptos<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo isset($this->datos['TOTALES'][$id_carrier]['TOTAL_BAJA']) ? $this->datos['TOTALES'][$id_carrier]['TOTAL_BAJA'] : '' ?></td>
            <td class="celda_cliente descripcion_cobro<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>">Bajas</td>
            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <th class="celda_cliente numero<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo (isset($this->datos['TOTALES'][$id_carrier]['datos'][$i]['BAJA']) ? $this->numero($this->datos['TOTALES'][$id_carrier]['datos'][$i]['BAJA']) : '') ?>&nbsp;</th>
            <?php if($i==15): ?>
                <td class="numero celda_total suscriptos<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo isset($this->datos['TOTALES'][$id_carrier]['TOTAL_BAJA']) ? $this->datos['TOTALES'][$id_carrier]['TOTAL_BAJA'] : '' ?></td>
                <td class="celda_cliente descripcion_cobro<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>">Bajas</td>
                <?php endif; ?>
            <?php endfor; ?>

            <td class="numero celda_total suscriptos<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo isset($this->datos['TOTALES'][$id_carrier]['TOTAL_BAJA']) ? $this->datos['TOTALES'][$id_carrier]['TOTAL_BAJA'] : '' ?></td>
            <td class="celda_cliente borde_derecha descripcion_cobro<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>">Bajas</td>
        </tr>
            <?php $carriers_procesados++; ?>
            <?php endforeach; ?>

    </tfoot>

    <tbody>
        <?php $imprimir_cabecera = false; ?>
        <?php for($hora=0; $hora<24; $hora++): ?>
        <?php
            $rowspan_hora = '';
            $cantidad_carriers = count($this->carriers_promocion);
            if($cantidad_carriers > 1) {
                $rowspan_hora = ' rowspan="'. ($cantidad_carriers*2) .'"';
            }
            $carriers_procesados = 0;

        ?>
        <?php foreach($this->carriers_promocion as $id_carrier): ?>
        <tr>
            <td class="celda_vacia"></td>
            <?php if($carriers_procesados == 0): ?>
            <td class="alias<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"<?php echo $rowspan_hora ?>><?php echo ($hora < 10 ? '0'.$hora : $hora) ?>&nbsp;hs.</td>
            <?php endif; ?>
            <td rowspan="2" class="carrier<?php echo ' ' . strtolower($this->carriers[$id_carrier]) ?><?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo $this->carriers[$id_carrier] ?></td>
            <td class="numero celda_total suscriptos<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo isset($this->datos[$hora][$id_carrier]['TOTAL_ALTA']) ? $this->datos[$hora][$id_carrier]['TOTAL_ALTA'] : '' ?></td>
            <td class="descripcion_cobro<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>">Altas</td>
            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <th class="numero<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?><?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo (isset($this->datos[$hora][$id_carrier]['datos'][$i]['ALTA']) ? $this->numero($this->datos[$hora][$id_carrier]['datos'][$i]['ALTA']) : '')  ?>&nbsp;</th>
                <?php if($i==15): ?>
                    <?php if($carriers_procesados == 0): ?>
                    <td class="alias<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"<?php echo $rowspan_hora ?>><?php echo ($hora < 10 ? '0'.$hora : $hora) ?>&nbsp;hs.</td>
                    <?php endif; ?>
                    <td rowspan="2" class="carrier<?php echo ' ' . strtolower($this->carriers[$id_carrier]) ?><?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo $this->carriers[$id_carrier] ?></td>
                    <td class="numero celda_total suscriptos<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo isset($this->datos[$hora][$id_carrier]['TOTAL_ALTA']) ? $this->datos[$hora][$id_carrier]['TOTAL_ALTA'] : '' ?></td>
                    <td class="descripcion_cobro<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>">Altas</td>
                <?php endif; ?>
            <?php endfor; ?>

            <?php if($carriers_procesados == 0): ?>
            <td class="alias<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"<?php echo $rowspan_hora ?>><?php echo ($hora < 10 ? '0'.$hora : $hora) ?>&nbsp;hs.</td>
            <?php endif; ?>
            <td rowspan="2" class="carrier<?php echo ' ' . strtolower($this->carriers[$id_carrier]) ?><?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo $this->carriers[$id_carrier] ?></td>
            <td class="numero celda_total suscriptos<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo isset($this->datos[$hora][$id_carrier]['TOTAL_ALTA']) ? $this->datos[$hora][$id_carrier]['TOTAL_ALTA'] : '' ?></td>
            <td class="borde_derecha descripcion_cobro<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>">Altas</td>

        </tr>
        <tr>
            <td class="celda_vacia"></td>
            <td class="numero celda_total suscriptos<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo isset($this->datos[$hora][$id_carrier]['TOTAL_BAJA']) ? $this->datos[$hora][$id_carrier]['TOTAL_BAJA'] : '' ?></td>
            <td class="celda_cliente descripcion_cobro<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>">Bajas</td>
            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <th class="celda_cliente<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?> numero<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo (isset($this->datos[$hora][$id_carrier]['datos'][$i]['BAJA']) ? $this->numero($this->datos[$hora][$id_carrier]['datos'][$i]['BAJA']) : '') ?>&nbsp;</th>
            <?php if($i==15): ?>
                <td class="numero celda_total suscriptos<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo isset($this->datos[$hora][$id_carrier]['TOTAL_BAJA']) ? $this->datos[$hora][$id_carrier]['TOTAL_BAJA'] : '' ?></td>
                <td class="celda_cliente descripcion_cobro<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>">Bajas</td>
            <?php endif; ?>
            <?php endfor; ?>

            <td class="numero celda_total suscriptos<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>"><?php echo isset($this->datos[$hora][$id_carrier]['TOTAL_BAJA']) ? $this->datos[$hora][$id_carrier]['TOTAL_BAJA'] : '' ?></td>
            <td class="celda_cliente borde_derecha descripcion_cobro<?php echo ($this->hora_actual == $hora ? ' hora_actual' : '') ?>">Bajas</td>
        </tr>
        <?php $carriers_procesados++; ?>
        <?php endforeach; ?>

        <?php
        $imprimir_cabecera = ( $hora > 0 && ($hora % 5 == 0));
        ?>

        <?php if($imprimir_cabecera): ?>
        <tr>
            <th class="fondo_naranja borde_arriba" style="min-width: 50px; width: 50px;"><?php echo $this->promocion['numero'] ?></th>
            <th colspan="4" class="fondo_naranja"><?php echo $this->promocion['alias'] ?></th>

            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <th class="nro_dia<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>" title="<?php echo $this->nombres_dias_del_mes[$i]['nombre_dia'] ?>"><?php echo $i ?></th>
                <?php if($i==15): ?>
                <th colspan="4" class="fondo_naranja"><?php echo $this->promocion['numero'] ?>&nbsp;-&nbsp;<?php echo $this->promocion['alias'] ?></th>
                <?php endif; ?>
            <?php endfor; ?>

            <th colspan="4" class="fondo_naranja"><?php echo $this->promocion['alias'] ?></th>
            <th class="fondo_naranja totales borde_derecha">Totales</th>
        </tr>
        <?php endif; ?>



        <?php endfor; ?>

    </tbody>
</table>

<?php endif; ?>