<?php if( !$this->es_movil ){?>

    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
            <meta name="viewport" content="initial-scale=1.0, width=device-width" />
            <title>ENTERMOVIL</title>
        </head>
        <body>

        <table width="<?php echo $this->formato['ancho'] ?>" border="0" cellspacing="0" cellpadding="0" id="principal" align="center">

            <tr>
                <td valign="center"><h2 style="color: black; text-align: center; padding: 0;">Acceso Restringido</h2></td>
            </tr>
            <tr>
                <td valign="center">
                    <h4 style="color: black; text-align: center; margin: 0;">Debe conectarse desde la red 3g de su celular</h4>
                    <hr/>
                </td>
            </tr>

        </table>

        </body>
    </html>
<?php }else{ ?>

    <div style="width: <?php echo $this->ua['ancho_tabla'] .'px'?>; background: #ffffff">

        <table id="navegador" align="center" width="<?php echo $this->ua['ancho_tabla'] . 'px'?>" cellspacing="0" cellpadding="0" border="0">
            <tr>
                <td><img class="menu" src="/<?php echo $this->ua['borde_arriba'] ?>" alt="NAVEGADOR" /></td>
            </tr>
        </table>
        <table id="tabla_suscripcion" width="<?php echo $this->ua['ancho_tabla'] . 'px'?>" border="0" cellspacing="2" cellpadding="5" align="center" bgcolor = "white">

            <tr>
                <td valign="center"><h1 style="color: black; text-align: center; padding: 0;">Acceso Restringido</h1></td>
            </tr>
            <tr style="line-height: 100%">
                <td valign="center">
                    <h4 style="color: black; text-align: center; margin: 0;">Debe conectarse desde la red 3g de su celular</h4>
                </td>
            </tr>
            <tr style="line-height: 100%">
                <td valign="center">
                    <h3 style="color: black; text-align: center; margin: 0;">Favor enviar PORTAL al 35500 para suscribirse</h3>
                </td>
            </tr>
        </table>
        <table id="borde_abajo" align="center" width="<?php echo $this->ua['ancho_tabla'] . 'px'?>" cellspacing="0" cellpadding="0" border="0">
            <tr>
                <td><img class="menu" src="/<?php echo $this->ua['borde_abajo'] ?>" alt="BORDE_ABAJO"></td>
            </tr>
        </table>
    </div>
<?php } ?>

