<table width="<?php echo $this->ancho_tabla ?>" border="0" cellspacing="0" cellpadding="0" id="principal" align="center">
    <tr>
        <td valign="center"><img src="http://www.entermovil.com.py/<?php echo $this->ua['imagen_logo'] ?>" alt="<?php echo $this->proveedor ?>"></td>
    </tr>
    <tr>
        <td valign="center"><h2 style="color: green; text-align: center; padding: 0;"><?php echo $this->servicio ?></h2></td>
    </tr>
    <tr>
        <td valign="center">
            <h4 style="color: black; text-align: center; margin: 0;"><?php echo $this->descripcion ?></h4>
            <hr/>
        </td>
    </tr>
    <tr>
        <td valign="center"><h3 style="text-align: center;"><?php echo $this->mensaje ?></h3></td>
    </tr>
    <tr>
        <td valign="center"><a href="http://mobi.quepachoo.com/emdown/?contenido=CANCION-01.mp3&auth=e7c2e04cd3caf1e79c85a8d91d962ad69d6c2b0d33bac95640f85424ec4a6a69">Prueba Descarga</a></td>
    </tr>

</table>
