<center>
    <section id="login" data-role="page">
        <header data-role="header">
            <h1>TwitterSMS</h1>
        </header>
        <article data-role="content" data-ajax="false">
            <form name="form1" method="post" action="/noticias/login" data-ajax="false">
                <div data-role="fieldcontain" class="ui-hide-label">
                    <!--<label for="txtuser">Usuario:</label>-->
                    <input type="text" name="login_user" id="login_user" value="" placeholder="Nombre" />
                </div>
                <div data-role="fieldcontain" class="ui-hide-label">
                    <!--<label for="txtpassword">Contraseña:</label>-->
                    <input type="password" name="login_pass" id="login_pass" value="" placeholder="Contraseña" />
                </div>
                <td><input type="submit" name="Submit" value="Ingresar" id="submitbutton" data-ajax="false"></td>
            </form>
        </article>
    </section>
</center>
