<?php

$front = Zend_Controller_Front::getInstance();
$bootstrap = $front->getParam("bootstrap");
$logger = $bootstrap->getResource('Logger');

?>
<div id="bloque_mes">
    Mes Seleccionado:&nbsp;
    <select id="mes" name="mes">
        <?php foreach($this->rango_seleccion as $rango): ?>
        <option value="<?php echo $rango['anho'].'-'.($rango['mes']<10? '0'.$rango['mes'] : $rango['mes']) ?>"<?php echo ($rango['selected'] == 'selected' ? ' selected="selected"' : '') ?>><?php echo $rango['descripcion'] ?></option>
        <?php endforeach; ?>
    </select>
</div>
<?php if( !is_null( $this->datos ) ):?>

    <?php foreach($this->datos['datos'] as $carrier => $datos_id_carrier): ?>

        <table class="tabla_pautas">
            <thead>
                <tr>
                    <th colspan="6" class="ultima_celda fondo_naranja_ultima borde_derecha" style="height: 25px; border-bottom: none;"><?php echo $carrier?></th>
                </tr>
                <tr>
                    <th class="fondo_naranja alias">Duracion</th>
                    <th class="fondo_naranja alias">Tarifa</th>
                    <th class="fondo_naranja alias">Cantidad</th>
                    <th class="fondo_naranja alias">Total Bruto</th>
                    <th class="fondo_naranja alias">Total Neto</th>
                    <th class="fondo_naranja alias borde_derecha ultima_celda">Monto Proveedor</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach( $datos_id_carrier['tipos'] as $tipo => $datos_tipo ):?>
                    <tr>
                        <td class="alias"><?php echo $datos_tipo['descripcion']?></td>
                        <td class="numero"><?php echo $datos_tipo['costo_usd']?></td>
                        <td class="numero"><?php echo $this->numero($datos_tipo['cantidad'])?></td>
                        <td class="numero"><?php echo $this->numero($datos_tipo['total_bruto_gs'])?></td>
                        <td class="numero"><?php echo $this->numero($datos_tipo['total_neto_gs'])?></td>
                        <td class="numero borde_derecha ultima_celda"><?php echo $this->numero($datos_tipo['total_monto_proveedor'])?></td>
                    </tr>
                <?php endforeach;?>
            </tbody>
            <tfoot>
                <tr>
                    <td class="alias celda_vacia"></td>
                    <td class="fondo_naranja alias">Total</td>
                    <td class="fondo_naranja numero"><?php echo $this->numero($datos_id_carrier['totales']['cantidad'])?></td>
                    <td class="fondo_naranja numero"><?php echo $this->numero($datos_id_carrier['totales']['total_neto_gs'])?></td>
                    <td class="fondo_naranja numero"><?php echo $this->numero($datos_id_carrier['totales']['total_neto_gs'])?></td>
                    <td class="fondo_naranja numero ultima_celda"><a style="color: black;text-decoration: underline" title="Detalles <?php echo $carrier.' '.$this->anho.'-'.$this->mes ?>" href="/reportes/backtones-totales/carrier/<?php echo $this->carriers[$carrier]?>/fecha/<?php echo $this->anho.'-'.$this->mes?>"><?php echo $this->numero($datos_id_carrier['totales']['total_monto_proveedor'])?></a></td>
                </tr>
            </tfoot>
        </table>
    <?php endforeach;?>
    <table class="tabla_pautas">
        <thead>
            <tr>
                <th class="alias celda_vacia"></th>
                <th rowspan="2" class="centrar fondo_naranja alias">Totales</th>
                <th class="fondo_naranja alias">Cantidad</th>
                <th class="fondo_naranja alias">Total Bruto</th>
                <th class="fondo_naranja alias">Total Neto</th>
                <th class="fondo_naranja alias borde_derecha ultima_celda">Monto Proveedor</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="alias celda_vacia"></td>
                <td class="fondo_naranja"></td>
                <td class="numero"><?php echo $this->numero($this->datos['totales_generales']['cantidad'])?></td>
                <td class="numero"><?php echo $this->numero($this->datos['totales_generales']['total_bruto_gs'])?></td>
                <td class="numero"><?php echo $this->numero($this->datos['totales_generales']['total_neto_gs'])?></td>
                <td class="numero borde_derecha ultima_celda"><?php echo $this->numero($this->datos['totales_generales']['total_monto_proveedor'])?></td>
            </tr>
        </tbody>
    </table>
<?php else: ?>
    <div class="bloque_mensaje">
        <p>No existen datos para este proveedor y mes</p>
    </div>

<?php endif; ?>




