
<div id="bloque_mes">
    Mes Seleccionado:&nbsp;
    <select id="mes" name="mes">
        <?php foreach($this->rango_seleccion as $rango): ?>
        <option value="<?php echo $rango['anho'].'-'.($rango['mes']<10? '0'.$rango['mes'] : $rango['mes']) ?>"<?php echo ($rango['selected'] == 'selected' ? ' selected="selected"' : '') ?>><?php echo $rango['descripcion'] ?></option>
        <?php endforeach; ?>
    </select>
</div>

<div id="bloque_instructivo">
    <h3>Referencias de Cobros</h3>
    <p>Precio Público = Gs. 2.000 sin IVA por cada contenido cobrado y entregado</p>
    <p>25% Enter Movil = Gs. 500</p>
    <p>75% Otros = Gs. 1.500 (Teléfonica = 70% / Licenciatario 5%)</p>
    <p><span style="width: 30px; background-color: #79eb74; display: block; float: left;">&nbsp;</span>&nbsp;= Día de Envío</p>
    <p><span style="width: 30px; background-color: #fff835; display: block; float: left;">&nbsp;</span>&nbsp;= Día Actual</p>
    <p>Ubicación de Productos de mayor a menor según cantidad de suscriptos</p>
</div>
<table class="tabla_reporte">
    <thead>
        <tr>
            <th class="celda_vacia"></th>
            <th colspan="3" class="borde_arriba borde_derecha" style="height: 25px; border-bottom: none;">Mes: <?php echo $this->nombre_mes ?> / Año: <?php echo $this->anho ?></th>
            <th colspan="<?php echo (2 + $this->cantidad_dias) ?>" class="celda_vacia"></th><!-- cantidad dias + 2 columnas -->
        </tr>
        <tr>
            <th class="fondo_naranja borde_arriba" style="min-width: 50px; width: 50px;">35500</th>
            <th colspan="3" class="fondo_naranja borde_arriba">Detalles Cobros</th>

            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <th class="nro_dia borde_arriba<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>" title="<?php echo $this->nombres_dias_del_mes[$i]['nombre_dia'] ?>"><?php echo $i ?></th>
            <?php endfor; ?>

            <th class="fondo_naranja totales borde_arriba">Totales</th>
            <th class="fondo_naranja porcentaje borde_arriba">% Liquidacion</th>
        </tr>

    </thead>
    <tfoot>
        <tr>
            <th class="celda_vacia"></th>
            <th rowspan="3">Totales</th>
            <th rowspan="3"><?php echo $this->numero($this->cobros_x_mes['TOTALES_MES']['total_suscriptos']) ?></th>
            <th class="descripcion_cobro">Cobros</th>

            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <th class="numero<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero($this->cobros_x_mes['TOTALES_MES']['datos_cobros'][$i]['total_cobros']) ?>&nbsp;</th>
            <?php endfor; ?>

            <th class="numero borde_derecha celda_total"><?php echo $this->numero($this->cobros_x_mes['TOTALES_MES']['total_cobros']) ?>&nbsp;</th>

            <th class="celda_vacia"></th>
        </tr>
        <tr>
            <th class="celda_vacia"></th>
            <th class="descripcion_cobro celda_cliente">ENTER 500gs.</th>

            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <th class="numero celda_cliente"><?php echo $this->numero($this->cobros_x_mes['TOTALES_MES']['datos_cobros'][$i]['total_bruto_cliente']) ?>&nbsp;</th>
            <?php endfor; ?>

            <th class="numero celda_cliente borde_derecha celda_total"><?php echo $this->numero($this->cobros_x_mes['TOTALES_MES']['total_bruto_cliente']) ?>&nbsp;</th>

            <th class="celda_vacia"></th>
        </tr>
        <tr>
            <th class="celda_vacia"></th>
            <th class="descripcion_cobro">OTROS 1.500gs.</th>

            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <th class="numero<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero($this->cobros_x_mes['TOTALES_MES']['datos_cobros'][$i]['total_bruto_otros']) ?>&nbsp;</th>
            <?php endfor; ?>

            <th class="numero borde_derecha celda_total"><?php echo $this->numero($this->cobros_x_mes['TOTALES_MES']['total_bruto_otros']) ?>&nbsp;</th>

            <th class="celda_vacia"></th>
        </tr>
    </tfoot>

    <tbody>

        <?php foreach($this->promociones as $promocion): ?>
        <tr>
            <td rowspan="3" class="celda_vacia"></td>
            <td rowspan="3" class="alias"><?php echo $promocion['alias'] ?></td>
            <td rowspan="3" class="suscriptos"><?php echo $this->numero($this->cobros_x_mes[$promocion['alias']]['total_suscriptos']) ?></td>
            <td class="descripcion_cobro">Cobros</td>

            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <td class="numero<?php echo (in_array($this->nombres_dias_del_mes[$i]['dia_semana'], $this->calendario_envios[$promocion['id_promocion']]) ? ' dia_envio' : '') ?><?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero($this->cobros_x_mes[$promocion['alias']]['datos_cobros'][$i]['total_cobros']) ?>&nbsp;</td>
            <?php endfor; ?>

            <td class="numero celda_total"><?php echo $this->numero($this->cobros_x_mes[$promocion['alias']]['total_cobros']) ?>&nbsp;</td>
            <td rowspan="3" class="numero_porcentaje" title="<?php echo $promocion['alias'] ?>"><?php echo $this->porcentaje($this->cobros_x_mes[$promocion['alias']]['total_cobros'] / $this->cobros_x_mes['TOTALES_MES']['total_cobros']) ?><br /><span style="font-size: 10px;"><?php echo $promocion['alias'] ?></span></td>
        </tr>

        <tr>
            <td class="descripcion_cobro celda_cliente">ENTER 500gs.</td>

            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <td class="monto_gs celda_cliente"><?php echo $this->numero($this->cobros_x_mes[$promocion['alias']]['datos_cobros'][$i]['total_bruto_cliente']) ?></td>
            <?php endfor; ?>

            <td class="monto_gs celda_cliente celda_total"><?php echo $this->numero($this->cobros_x_mes[$promocion['alias']]['total_bruto_cliente']) ?>&nbsp;</td>

        </tr>
        <tr>
            <td class="descripcion_cobro">Otros 1.500gs.</td>

            <?php for($i=1; $i<=$this->cantidad_dias; $i++): ?>
            <td class="monto_gs<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero($this->cobros_x_mes[$promocion['alias']]['datos_cobros'][$i]['total_bruto_otros']) ?></td>
            <?php endfor; ?>

            <td class="monto_gs celda_total"><?php echo $this->numero($this->cobros_x_mes[$promocion['alias']]['total_bruto_otros']) ?>&nbsp;</td>
        </tr>

        <tr>
            <td class="celda_vacia"></td>
            <td colspan="<?php echo (3 + $this->cantidad_dias + 2) ?>" class="separador">&nbsp;</td>
        </tr>
        <?php endforeach; ?>

    </tbody>
</table>