<?php

$front = Zend_Controller_Front::getInstance();
$bootstrap = $front->getParam("bootstrap");
$logger = $bootstrap->getResource('Logger');

?>
<div id="bloque_mes">
    Mes Seleccionado:&nbsp;
    <select id="mes" name="mes">
        <?php foreach($this->rango_seleccion as $rango): ?>
        <option value="<?php echo $rango['anho'].'-'.($rango['mes']<10? '0'.$rango['mes'] : $rango['mes']) ?>"<?php echo ($rango['selected'] == 'selected' ? ' selected="selected"' : '') ?>><?php echo $rango['descripcion'] ?></option>
        <?php endforeach; ?>
    </select>
</div>

<div id="bloque_instructivo">
    <p><span style="width: 30px; background-color: #fff835; display: block; float: left;">&nbsp;</span>&nbsp;= Día Actual</p>
    <p><span style="width: 30px; background-color: #BBCCFF; display: block; float: left;">&nbsp;</span>&nbsp;= Día Domingo</p>
</div>

<?php /*print_r($this->datos);exit;*/?>


    <?php foreach($this->datos as $id_promocion => $promocion): ?>

        <table id="tabla_numero_<?php echo 6767 ?>" class="tabla_reporte">
            <thead>
                <tr>
                    <th class="celda_vacia"></th>
                    <th colspan="2" class="borde_arriba" style="height: 25px; border-bottom: none;">Mes: <?php echo $this->nombre_mes ?> / Año: <?php echo $this->anho ?></th>
                    <?php for($i=1; $i<=15; $i++): ?>
                    <th class="borde_arriba<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?><?php echo ($this->nombres_dias_del_mes[$i]['dia_semana'] == 0 ? ' domingo' : '') ?>"><?php echo $this->nombres_dias_del_mes[$i]['nombre_dia'] ?></th>
                    <?php endfor; ?>
                    <th colspan="2" class="borde_arriba" style="height: 25px; border-bottom: none;">Mes: <?php echo $this->nombre_mes ?> / Año: <?php echo $this->anho ?></th>
                    <?php for($i=16; $i<=$this->cantidad_dias; $i++): ?>
                    <th class="borde_arriba <?php echo ( $i == $this->cantidad_dias)? 'borde_derecha':''?> <?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?><?php echo ($this->nombres_dias_del_mes[$i]['dia_semana'] == 0 ? ' domingo' : '') ?>"><?php echo $this->nombres_dias_del_mes[$i]['nombre_dia'] ?></th>
                    <?php endfor; ?>
                    <th colspan="<?php echo (3 + $this->cantidad_dias) ?>" class="celda_vacia"></th><!-- cantidad dias + 2 columnas -->
                </tr>
                <tr>
                    <th class="fondo_naranja borde_arriba" style="min-width: 50px; width: 50px;"><?php echo 6767 ?></th>
                    <th colspan="2" class="fondo_naranja borde_arriba">Detalles Cobros</th>

                    <?php for($i=1; $i<=15; $i++): ?>
                        <th class="nro_dia<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>" title="<?php echo $this->nombres_dias_del_mes[$i]['nombre_dia'] ?>"><?php echo $i ?></th>
                    <?php endfor; ?>

                    <th colspan="2" class="fondo_naranja borde_arriba"><?php echo "6767" ?>&nbsp;</th>

                    <?php for($i=16; $i<=$this->cantidad_dias; $i++): ?>
                    <th class="nro_dia<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>" title="<?php echo $this->nombres_dias_del_mes[$i]['nombre_dia'] ?>"><?php echo $i ?></th>
                    <?php endfor; ?>

                    <th class="fondo_naranja totales borde_arriba borde_derecha">Totales</th>
                </tr>

            </thead>

            <tr>
                <th class="celda_vacia"></th>
                <th class="alias" rowspan="7"><?php echo $id_promocion ?></th>
                <th class="descripcion_cobro celda_cliente">ALTAS</th>

                <?php for($i=1; $i<=15; $i++): ?>
                    <th class="numero celda_cliente<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero($promocion['mes'][$i]['ALTA']) ?>&nbsp;</th>
                <?php endfor; ?>

                <th class="alias" rowspan="7"><?php echo $id_promocion ?></th>
                <th class="descripcion_cobro celda_cliente">ALTAS</th>

                <?php for($i=16; $i<=$this->cantidad_dias; $i++): ?>
                    <th class="numero celda_cliente<?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero($promocion['mes'][$i]['ALTA']) ?>&nbsp;</th>
                <?php endfor; ?>

                <th class="numero celda_total celda_cliente borde_derecha"><?php echo $this->numero($promocion['totales']['total_altas']) ?>&nbsp;</th>
            </tr>
            <tr>
                <th class="celda_vacia"></th>
                <th class="descripcion_cobro celda_cliente">BAJAS</th>

                <?php for($i=1; $i<=15; $i++): ?>
                    <th class="numero celda_cliente"><?php echo $this->numero($promocion['mes'][$i]['BAJA']) ?>&nbsp;</th>
                <?php endfor; ?>

                <th class="descripcion_cobro celda_cliente">BAJAS</th>

                <?php for($i=16; $i<=$this->cantidad_dias; $i++): ?>
                    <th class="numero celda_cliente"><?php echo $this->numero($promocion['mes'][$i]['BAJA']) ?>&nbsp;</th>
                <?php endfor; ?>

                <th class="numero celda_cliente celda_total borde_derecha"><?php echo $this->numero($promocion['totales']['total_bajas']) ?>&nbsp;</th>

                <th class="celda_vacia"></th>
            </tr>

            <tr>
                <th class="celda_vacia"></th>
                <th class="descripcion_cobro celda_cliente">NETO SUSCRIPTOS</th>

                <?php for($i=1; $i<=15; $i++): ?>
                    <th class="numero celda_cliente"><?php echo $this->numero($promocion['mes'][$i]['neto_suscriptos']) ?>&nbsp;</th>
                <?php endfor; ?>

                <th class="descripcion_cobro celda_cliente">NETO SUSCRIPTOS</th>

                <?php for($i=16; $i<=$this->cantidad_dias; $i++): ?>
                    <th class="numero celda_cliente"><?php echo $this->numero($promocion['mes'][$i]['neto_suscriptos']) ?>&nbsp;</th>
                <?php endfor; ?>

                <th class="numero celda_cliente celda_total borde_derecha"><?php echo $this->numero($promocion['totales']['total_suscriptos']) ?>&nbsp;</th>
                <th class="celda_vacia"></th>
            </tr>
            <tr>
                <th class="celda_vacia"></th>
                <th class="descripcion_cobro">COBROS</th>

                <?php for($i=1; $i<=15; $i++): ?>
                    <th class="numero <?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero($promocion['mes'][$i]['total_cobros']) ?>&nbsp;</th>
                <?php endfor; ?>

                <th class="descripcion_cobro celda_cliente">COBROS</th>

                <?php for($i=16; $i<=$this->cantidad_dias; $i++): ?>
                    <th class="numero <?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero($promocion['mes'][$i]['total_cobros']) ?>&nbsp;</th>
                <?php endfor; ?>

                <th class="numero celda_total borde_derecha"><?php echo $this->numero($promocion['totales']['total_cobros']) ?>&nbsp;</th>
                <th class="celda_vacia"></th>
            </tr>
            <?php if( $id_promocion == 'YA'|| $id_promocion == 'SEMANA' ):?>
                <tr>
                    <th class="celda_vacia"></th>
                    <th class="descripcion_cobro">SUSCRIPTOS A COBRAR</th>

                    <?php for($i=1; $i<=15; $i++): ?>
                        <th class="numero <?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero(isset($promocion['cobros_x_dia_semana'][$this->nombres_dias_del_mes[$i]['dia_semana']])?$promocion['cobros_x_dia_semana'][$this->nombres_dias_del_mes[$i]['dia_semana']]:0) ?>&nbsp;</th>
                    <?php endfor; ?>

                    <th class="descripcion_cobro celda_cliente">SUSCRIPTOS A COBRAR</th>

                    <?php for($i=16; $i<=$this->cantidad_dias; $i++): ?>
                        <th class="numero <?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero(isset($promocion['cobros_x_dia_semana'][$this->nombres_dias_del_mes[$i]['dia_semana']])?$promocion['cobros_x_dia_semana'][$this->nombres_dias_del_mes[$i]['dia_semana']]:0) ?>&nbsp;</th>
                    <?php endfor; ?>

                    <th class="numero celda_total borde_derecha"><?php echo $this->numero(0) ?>&nbsp;</th>
                    <th class="celda_vacia"></th>
                </tr>
                <!--<tr>
                    <th class="celda_vacia"></th>
                    <th class="descripcion_cobro">SUSCRIPTOS A COBRAR COBROS</th>

                    <?php /*for($i=1; $i<=15; $i++): */?>
                        <th class="numero <?php /*echo ($this->dia_hoy == $i ? ' dia_actual' : '') */?>"><?php /*echo $this->numero($promocion['cobros_x_dia_semana_cobros'][$this->nombres_dias_del_mes[$i]['dia_semana']]) */?>&nbsp;</th>
                    <?php /*endfor; */?>

                    <th class="descripcion_cobro celda_cliente">SUSCRIPTOS A COBRAR COBROS</th>

                    <?php /*for($i=16; $i<=$this->cantidad_dias; $i++): */?>
                        <th class="numero <?php /*echo ($this->dia_hoy == $i ? ' dia_actual' : '') */?>"><?php /*echo $this->numero($promocion['cobros_x_dia_semana_cobros'][$this->nombres_dias_del_mes[$i]['dia_semana']]) */?>&nbsp;</th>
                    <?php /*endfor; */?>

                    <th class="numero celda_total borde_derecha"><?php /*echo $this->numero(0) */?>&nbsp;</th>
                    <th class="celda_vacia"></th>
                </tr>-->
            <?php elseif($id_promocion=='MES'):?>
                <tr>
                    <th class="celda_vacia"></th>
                    <th class="descripcion_cobro">SUSCRIPTOS A COBRAR</th>

                    <?php for($i=1; $i<=15; $i++): ?>
                        <th class="numero <?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero(isset( $promocion['cobros_x_dia_semana'][$i])? $promocion['cobros_x_dia_semana'][$i]:0) ?>&nbsp;</th>
                    <?php endfor; ?>

                    <th class="descripcion_cobro celda_cliente">SUSCRIPTOS A COBRAR</th>

                    <?php for($i=16; $i<=$this->cantidad_dias; $i++): ?>
                        <th class="numero <?php echo ($this->dia_hoy == $i ? ' dia_actual' : '') ?>"><?php echo $this->numero(isset( $promocion['cobros_x_dia_semana'][$i])? $promocion['cobros_x_dia_semana'][$i]:0) ?>&nbsp;</th>
                    <?php endfor; ?>

                    <th class="numero celda_total borde_derecha"><?php echo $this->numero(0) ?>&nbsp;</th>
                    <th class="celda_vacia"></th>
                </tr>
                <!--<tr>
                    <th class="celda_vacia"></th>
                    <th class="descripcion_cobro">SUSCRIPTOS A COBRAR COBROS</th>

                    <?php /*for($i=1; $i<=15; $i++): */?>
                        <th class="numero <?php /*echo ($this->dia_hoy == $i ? ' dia_actual' : '') */?>"><?php /*echo $this->numero(isset( $promocion['cobros_x_dia_semana_cobros'][$i])? $promocion['cobros_x_dia_semana_cobros'][$i]:0) */?>&nbsp;</th>
                    <?php /*endfor; */?>

                    <th class="descripcion_cobro celda_cliente">SUSCRIPTOS A COBRAR COBROS</th>

                    <?php /*for($i=16; $i<=$this->cantidad_dias; $i++): */?>
                        <th class="numero <?php /*echo ($this->dia_hoy == $i ? ' dia_actual' : '') */?>"><?php /*echo $this->numero(isset( $promocion['cobros_x_dia_semana_cobros'][$i])? $promocion['cobros_x_dia_semana_cobros'][$i]:0) */?>&nbsp;</th>
                    <?php /*endfor; */?>

                    <th class="numero celda_total borde_derecha"><?php /*echo $this->numero(0) */?>&nbsp;</th>
                    <th class="celda_vacia"></th>
                </tr>-->
            <?php endif;?>

            <tr>
                <th class="celda_vacia"></th>
                <th class="descripcion_cobro celda_cliente">NETO ENTER</th>

                <?php for($i=1; $i<=15; $i++): ?>
                    <th class="numero celda_cliente"><?php echo $this->numero($promocion['mes'][$i]['total_neto_gs']) ?>&nbsp;</th>
                <?php endfor; ?>

                <th class="descripcion_cobro celda_cliente">NETO ENTER</th>

                <?php for($i=16; $i<=$this->cantidad_dias; $i++): ?>
                    <th class="numero celda_cliente"><?php echo $this->numero($promocion['mes'][$i]['total_neto_gs']) ?>&nbsp;</th>
                <?php endfor; ?>

                <th class="numero celda_cliente celda_total borde_derecha"><?php echo $this->numero($promocion['totales']['total_neto']) ?>&nbsp;</th>
                <th class="celda_vacia"></th>
            </tr>

        </table>
    <?php endforeach; ?>



