<div id="bloque_promocion">

    Alias:&nbsp;
    <select id="alias" name="alias">
        <?php foreach($this->alias as $indice=>$alias): ?>
            <option value="<?php echo $alias['alias'] ?>"<?php echo ( $alias['alias'] == $this->nombre_alias ? ' selected="selected"': '') ?>><?php $alias['alias'] == $this->nombre_alias ? $alias['alias']: '';echo $alias['alias']?></option>
        <?php endforeach; ?>
    </select>

</div>
<?php if( !empty( $this->contenidos ) ):?>
    <table class="tabla_informe_pautas">
        <thread>
            <tr>
                <td class="fondo_naranja_ultima centrar ultima_celda" colspan="3">Contenidos Verificados</td>
            </tr>
            <tr>
                <td class="fondo_naranja centrar">Nro.</td>
                <td class="fondo_naranja centrar">Texto</td>
                <td class="fondo_naranja_ultima ultima_celda centrar">Largo</td>
            </tr>
        </thread>
        <?php foreach( $this->contenidos as $indice=> $mensaje ):?>
            <tr>
                <td><?php echo $indice ?></td>
                <td><?php echo $mensaje ?></td>
                <td class="ultima_celda"><?php echo strlen($mensaje) ?></td>
            </tr>
        <?php endforeach;?>
    </table>
    <div id="bloque_promocion">
        <a href="/reportes/insertar-contenidos-bd/alias/<?php echo $this->cargar?>/id_promocion/<?php echo $this->id_promocion ?>">
            <input type="button" value="Cargar">
        </a>
    </div>
<?php else: ?>
    <table class="tabla_informe_pautas">
        <thread>
            <tr>
                <td class="fondo_naranja_ultima centrar ultima_celda" colspan="3">No existen contenidos nuevos para cargar</td>
            </tr>
        </thread>
    </table>
<?php endif;?>

<script type="text/javascript">

    $(document).ready(function(){
        $("#alias").change(function(){
           window.location = '/reportes/informe-contenidos/alias/' + this.value;
        });
    });
</script>