<div id="bloque_mes">

    <p>
        Dia Seleccionado: <input type="text" id="datepicker" value="<?php echo (isset($this->fecha)) ? $this->fecha : date('Y-m-d') ?>" />
        <input type="button" id="boton_pautas" value="Cargar" >
    </p>
</div>

<?php $totales = array(
    'total_suscriptos' => 0,
    'total_altas_mes' => 0,
    'total_bajas_mes' => 0,
    'total_cobros_mes' => 0,
    'total_neto_mes' => 0,
    'total_altas' => 0,
    'total_bajas' => 0,
    'total_cobros' => 0,
    'total_neto' => 0,
); ?>
<!--Comentar terminar despues-->
<!--<?php print_r($this->canales) ?>-->

<?php foreach($this->canales as $canal): ?>
<table class="tabla_pautas">
        <thead>
            <tr>
                <th colspan ="8" class="ultima_celda fondo_naranja_ultima <?php echo $canal['css_titulo'] ?> "><?php echo $canal['descripcion'] ?></th>
            </tr>
            <!--Modifique-->
            <tr>
                <th class="fondo_naranja alias">Alias </th>
                <th class="fondo_naranja alias">Suscriptos</th>
                <th class="fondo_naranja altas_bajas">Altas Dia</th>
                <th class="fondo_naranja altas_bajas">Bajas Dia</th>
                <!--<th class="fondo_naranja altas_bajas">Cobros Dia</th>
                <th class="fondo_naranja alias">Neto Dia</th>-->
                <th class="fondo_naranja altas_bajas">Altas Mes</th>
                <th class="fondo_naranja altas_bajas">Bajas Mes</th>
                <th class="fondo_naranja altas_bajas">Cobros Mes</th>
                <th class="ultima_celda fondo_naranja_ultima alias">Neto Mes</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($canal['datos'] as $alias => $datos_alias): ?>

            <tr>
                <td align="center"><?php echo $alias; ?></td>
                <td class="numero"><?php echo $this->numero($datos_alias['SUSCRIPTOS']) ?></td>
                <td class="numero"><?php echo $this->numero($datos_alias['ALTA_HOY']) ?></td>
                <td class="numero"><?php echo $this->numero($datos_alias['BAJA_HOY']) ?></td>
                <!--<td class="numero"><?php /*echo $this->numero($datos_alias['COBROS_HOY']) */?></td>
                <td class="numero"><?php /*echo $this->numero($datos_alias['NETO_HOY']) */?> Gs.</td>-->

                <td class="numero"><?php echo $this->numero($datos_alias['ALTA']) ?></td>
                <td class="numero"><?php echo $this->numero($datos_alias['BAJA']) ?></td>
                <td class="numero"><?php echo $this->numero($datos_alias['COBROS']) ?></td>
                <td class="ultima_celda numero"><?php echo $this->numero($datos_alias['NETO']) ?> Gs.</td>
            </tr>
            <?php endforeach; ?>

        </tbody>
        <tfoot>
                <th class="fondo_naranja numero centrar">Totales</th>
                <th class="fondo_naranja numero"><?php echo  $this->numero($canal['totales']['TOTAL_SUSCRIPTOS']) ?></th>
                    <?php $totales['total_suscriptos'] = $totales['total_suscriptos'] + $canal['totales']['TOTAL_SUSCRIPTOS']?>

                <th class="fondo_naranja numero"><?php echo  $this->numero($canal['totales']['TOTAL_ALTA_HOY']) ?></th>
                    <?php $totales['total_altas_mes'] = $totales['total_altas_mes'] + $canal['totales']['TOTAL_ALTA_HOY'] ?>

                <th class="fondo_naranja numero"><?php echo  $this->numero($canal['totales']['TOTAL_BAJA_HOY']) ?></th>
                    <?php $totales['total_bajas_mes'] = $totales['total_bajas_mes'] + $canal['totales']['TOTAL_BAJA_HOY']?>

                <!--<th class="fondo_naranja numero"><?php /*echo  $this->numero($canal['totales']['TOTAL_COBROS_HOY']) */?></th>
                    <?php /*$totales['total_cobros_mes'] = $totales['total_cobros_mes'] + $canal['totales']['TOTAL_COBROS_HOY']*/?>

                <th class="fondo_naranja numero"><?php /*echo  $this->numero($canal['totales']['TOTAL_NETO_HOY']) */?> Gs.</th>
                    --><?php /*$totales['total_neto_mes'] = $totales['total_neto_mes'] + $canal['totales']['TOTAL_NETO_HOY']*/?>


                <th class="fondo_naranja numero"><?php echo $this->numero($canal['totales']['TOTAL_ALTA']) ?></th>
                    <?php $totales['total_altas'] = $totales['total_altas'] + $canal['totales']['TOTAL_ALTA']?>

                <th class="fondo_naranja numero""><?php echo $this->numero($canal['totales']['TOTAL_BAJA']) ?></th>
                    <?php $totales['total_bajas'] = $totales['total_bajas'] + $canal['totales']['TOTAL_BAJA']?>

                <th class="fondo_naranja numero""><?php echo $this->numero($canal['totales']['TOTAL_COBROS']) ?></th>
                    <?php $totales['total_cobros'] = $totales['total_cobros'] + $canal['totales']['TOTAL_COBROS']?>

                <th class="ultima_celda fondo_naranja_ultima numero""><?php echo $this->numero($canal['totales']['TOTAL_NETO']) ?> Gs.</th>
                    <?php $totales['total_neto'] = $totales['total_neto'] + $canal['totales']['TOTAL_NETO']?>
        </tfoot>
</table>
<?php endforeach; ?>

<table class="tabla_pautas">
    <thead>
        <tr>
            <th rowspan="2" class="fondo_naranja alias">Totales</th>
            <th class="fondo_naranja alias">Suscriptos</th>
            <th class="fondo_naranja altas_bajas">Altas Dia</th>
            <th class="fondo_naranja altas_bajas">Bajas Dia</th>
            <!--<th class="fondo_naranja altas_bajas">Cobros Dia</th>
            <th class="fondo_naranja alias">Neto Dia</th>-->
            <th class="fondo_naranja altas_bajas">Altas Mes</th>
            <th class="fondo_naranja altas_bajas">Bajas Mes</th>
            <th class="fondo_naranja altas_bajas">Cobros Mes</th>
            <th class="ultima_celda fondo_naranja_ultima alias">Neto Mes</th>
        </tr>

        <tr>
            <td class="numero"><?php echo $this->numero($totales["total_suscriptos"]) ?></td>
            <td class="numero"><?php echo $this->numero($totales["total_altas_mes"]) ?></td>
            <td class="numero"><?php echo $this->numero($totales["total_bajas_mes"]) ?></td>
            <!--<td class="numero"><?php /*echo $this->numero($totales["total_cobros_mes"]) */?></td>
            <td class="numero"><?php /*echo $this->numero($totales["total_neto_mes"]) */?> Gs.</td>-->

            <td class="numero"><?php echo $this->numero($totales["total_altas"]) ?></td>
            <td class="numero"><?php echo $this->numero($totales["total_bajas"]) ?></td>
            <td class="numero"><?php echo $this->numero($totales["total_cobros"]) ?></td>
            <td class="numero ultima_celda numero"><?php echo $this->numero($totales["total_neto"]) ?> Gs.</td>
        </tr>
    </thead>

</table>

