<div id="bloque_mes">
    <?php if($this->mostrar_lista_paises): ?>
    País:&nbsp;
    <select id="id_pais" name="id_pais">
        <?php foreach($this->paises as $pais): ?>
        <option value="<?php echo $pais['id_pais'] ?>" <?php echo ( $pais['id_pais']== $this->id_pais) ? 'selected=selected' . 'value='.$this->id_pais :''?>><?php echo $pais['nombre'] ?></option>
        <?php endforeach; ?>
    </select>
    <?php else: ?>
        País:&nbsp;<?php echo $this->nombre_pais ?>&nbsp;&nbsp;
    <?php endif; ?>

    Dia Seleccionado:&nbsp;
    <input type="text" id="datepicker" value="<?php echo (isset($this->fecha)) ? $this->fecha : date('Y-m-d') ?>" />
    <input type="button" id="cargar_resumen" value="Cargar">
</div>

<?php $Total_hoy = array(

    'Total_Cobros_Hoy' => 0,
    'Total_Total_Hoy' => 0,
    'Total_Neto_Hoy' => 0,
);
$total_foot = array(

    'Total_Foot_Cobros_Hoy' => 0,
    'Total_Foot_Total_Hoy' => 0,
    'Total_Foot_Neto_Hoy' => 0,
)
?>

<!--  <?php //print_r($this->carriers_numeros) ?>  -->
<?php foreach($this->carriers_numeros as $carrier_numero): ?>

<table id="tabla_resumen_<?php echo $this->nombre_carrier[$carrier_numero['id_carrier']] ?>_<?php echo $carrier_numero['numero'] ?>" class="tabla_reporte">
    <thead>
        <tr>
            <th  class=" <?php echo "carrier " . strtolower($this->nombre_carrier[$carrier_numero['id_carrier']]) . " borde_arriba" . " borde_derecha" ?> " colspan="10"  style="height: 20px; border-bottom: none; width: 400px"><?php echo $this->nombre_carrier[$carrier_numero['id_carrier']] ?></th>
        </tr>
        <tr>
            <th rowspan="2" class="fondo_naranja borde_arriba">Numero</th>
            <th rowspan="2" class="fondo_naranja borde_arriba">Alias</th>
            <th rowspan="2" class="fondo_naranja borde_arriba" style="width: 50px;">Precio</th>
            <th rowspan="2" class="fondo_naranja borde_arriba">Suscriptos</th>

            <th colspan="3" style="font-size: 12px; font-weight: bold;" class="borde_arriba"><?php echo $this->fecha?></th>
            <th colspan="3" style="font-size: 12px; font-weight: bold;" class="borde_arriba borde_derecha">Mes</th>

            <!--<th style="width: 50px;" class="sin_bordes">&nbsp;</th>-->

        </tr>

        <tr>
            <th class="fondo_naranja" style="width: 70px;">Cobros Día</th>
            <th class="fondo_naranja" style="width: 100px;">Total Día</th>
            <th class="fondo_naranja" style="width: 100px;">Neto Hoy</th>

            <th class="fondo_naranja" style="width: 70px;">Cobros Mes</th>
            <th class="fondo_naranja" style="width: 100px;">Total Mes</th>
            <th class="fondo_naranja borde_derecha" style="width: 100px;">Neto Enter</th>
        </tr>

    </thead>

    <tbody>
        <?php $primera_fila = true; ?>
        <?php foreach($this->promociones_carriers_numeros[$carrier_numero['id_carrier']][$carrier_numero['numero']] as $promocion_carrier_numero): ?>
        <!-- <?php //echo 'carrier_numero:[' . print_r($carrier_numero, true) . ']' ?> -->
        <tr>
            <?php if($primera_fila) {
                $cantidad_promociones = count($this->promociones_carriers_numeros[$carrier_numero['id_carrier']][$carrier_numero['numero']]);
                $primera_fila = false; ?>
                <td class="<?php echo "carrier " . strtolower($this->nombre_carrier[$carrier_numero['id_carrier']]) ?>" rowspan="<?php echo $cantidad_promociones ?>"><?php echo $carrier_numero['numero'] ?></td>
            <?php
            } ?>
            <td class="alias"><?php echo $promocion_carrier_numero['alias'] ?></td>
            <td class="monto_gs"><?php echo $this->numero($this->totales[$carrier_numero['id_carrier']][$carrier_numero['numero']][$promocion_carrier_numero['id_promocion']]['costo'], $this->totales[$carrier_numero['id_carrier']][$carrier_numero['numero']][$promocion_carrier_numero['id_promocion']]['decimal'])?></td>
            <td class="numero suscriptos"><?php echo $this->numero($promocion_carrier_numero['suscriptos']) ?></td>

            <td class="numero"><?php echo ( isset($carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']] ) ? $carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']]['total_cobros_hoy'] : "") ?></td>

            <?php  isset($carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']] ) ? $Total_hoy['Total_Cobros_Hoy']+= $carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']]['total_cobros_hoy'] : $Total_hoy['Total_Cobros_Hoy']+= 0 ?>

            <td class="monto_gs"><?php echo $this->numero( ( isset($carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']] ) ? ($carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']]['costo_gs'] == 0 ? $carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']]['total_bruto_usd'] : $carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']]['total_bruto_gs']) : ""), $this->totales[$carrier_numero['id_carrier']][$carrier_numero['numero']][$promocion_carrier_numero['id_promocion']]['decimal'])  ?></td>

            <?php  isset($carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']] ) ? ($carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']]['costo_gs'] == 0 ? $Total_hoy['Total_Total_Hoy'] += $carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']]['total_bruto_usd'] : $Total_hoy['Total_Total_Hoy'] += $carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']]['total_bruto_gs']) : ""  ?>

            <td class="monto_gs"><?php echo $this->numero(( isset($carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']]) ? ($carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']]['costo_gs'] == 0 ? $carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']]['total_neto_usd'] : $carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']]['total_neto_gs']) : ""), $this->totales[$carrier_numero['id_carrier']][$carrier_numero['numero']][$promocion_carrier_numero['id_promocion']]['decimal'])  ?></td>

            <?php  isset($carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']] ) ? ($carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']]['costo_gs'] == 0 ? $Total_hoy['Total_Neto_Hoy'] += $carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']]['total_neto_usd'] : $Total_hoy['Total_Neto_Hoy'] +=  $carrier_numero['cobros'][$promocion_carrier_numero['id_promocion']]['total_neto_gs'] ) : "" ?></td>


            <td class="numero"><?php echo $this->numero($this->totales[$carrier_numero['id_carrier']][$carrier_numero['numero']][$promocion_carrier_numero['id_promocion']]['cobros']) ?></td>
            <td class="monto_gs"><?php echo $this->numero($this->totales[$carrier_numero['id_carrier']][$carrier_numero['numero']][$promocion_carrier_numero['id_promocion']]['total_bruto'] , $this->totales[$carrier_numero['id_carrier']][$carrier_numero['numero']][$promocion_carrier_numero['id_promocion']]['decimal']) ?></td>
            <td class="monto_gs borde_derecha"><?php echo $this->numero($this->totales[$carrier_numero['id_carrier']][$carrier_numero['numero']][$promocion_carrier_numero['id_promocion']]['total_neto'] , $this->totales[$carrier_numero['id_carrier']][$carrier_numero['numero']][$promocion_carrier_numero['id_promocion']]['decimal']) ?></td>

            <!--<td class="sin_bordes">&nbsp;</td>-->

        </tr>
        <?php endforeach; ?>

    </tbody>

    <tfoot>
        <tr>

            <th colspan="3" class="fondo_naranja borde_arriba" align="center">Totales</th>
            <th align="right" class="fondo_naranja borde_arriba" style="width: 70px;"><?php echo $this->numero($this->sumatoria[$carrier_numero['id_carrier']][$carrier_numero['numero']]['TOTAL_SUSCRIPTOS']) ?></th>

            <th align="right" class="fondo_naranja borde_arriba" style="width: 70px;"><?php echo $this->numero( $Total_hoy['Total_Cobros_Hoy'],$this->totales[$carrier_numero['id_carrier']][$carrier_numero['numero']][$promocion_carrier_numero['id_promocion']]['decimal'] ) ?></th>
            <?php
                $total_foot['Total_Foot_Cobros_Hoy'] += $Total_hoy['Total_Cobros_Hoy'];
                $Total_hoy['Total_Cobros_Hoy'] = 0
            ?>
            <th align="right" class="fondo_naranja borde_arriba" style="width: 100px;"><?php echo $this->numero( $Total_hoy['Total_Total_Hoy'],$this->totales[$carrier_numero['id_carrier']][$carrier_numero['numero']][$promocion_carrier_numero['id_promocion']]['decimal'] ) ?></th>
            <?php
                $total_foot['Total_Foot_Total_Hoy'] += $Total_hoy['Total_Total_Hoy'];
                $Total_hoy['Total_Total_Hoy'] = 0
            ?>
            <th align="right" class="fondo_naranja borde_arriba" style="width: 100px;"><?php echo $this->numero( $Total_hoy['Total_Neto_Hoy'], $this->totales[$carrier_numero['id_carrier']][$carrier_numero['numero']][$promocion_carrier_numero['id_promocion']]['decimal'] ) ?></th>
            <?php
                $total_foot['Total_Foot_Neto_Hoy'] += $Total_hoy['Total_Neto_Hoy'];
                $Total_hoy['Total_Neto_Hoy'] = 0
            ?>
            <th align="right" class="fondo_naranja borde_arriba" style="width: 70px;"><?php echo $this->numero($this->sumatoria[$carrier_numero['id_carrier']][$carrier_numero['numero']]['TOTAL_COBROS']) ?></th>
            <th align="right" class="fondo_naranja borde_arriba" style="width: 100px;"><?php echo  $this->numero($this->sumatoria[$carrier_numero['id_carrier']][$carrier_numero['numero']]['TOTAL_BRUTO'], $this->sumatoria[$carrier_numero['id_carrier']][$carrier_numero['numero']]['decimal']) ?></th>
            <th align="right" class="fondo_naranja borde_arriba borde_derecha" style="width: 100px;"><?php echo $this->numero($this->sumatoria[$carrier_numero['id_carrier']][$carrier_numero['numero']]['TOTAL_NETO'] ,$this->sumatoria[$carrier_numero['id_carrier']][$carrier_numero['numero']]['decimal'])?></th>

        </tr>


    </tfoot>
</table>
<?php endforeach; ?>

<table id="tabla_resumen" class="tabla_reporte">
    <tr>
        <th rowspan="2" colspan="3" class="fondo_naranja borde_arriba" align="center" style="width:201px;">Totales</th>
        <th rowspan="2" class="fondo_naranja borde_arriba" style="width:70px">Suscriptos</th>

        <th colspan="3" style="font-size: 12px; font-weight: bold;" class="borde_arriba"><?php echo $this->fecha?></th>
        <th colspan="3" style="font-size: 12px; font-weight: bold;" class="borde_arriba borde_derecha">Mes</th>


    </tr>

    <tr>

        <th class="fondo_naranja borde_arriba" style="width:70px">Cobros</th>
        <th class="fondo_naranja borde_arriba" style="width:100px">Bruto</th>
        <th class="fondo_naranja borde_arriba" style="width:100px">Neto Enter</th>

        <th class="fondo_naranja borde_arriba" style="width:70px">Cobros</th>
        <th class="fondo_naranja borde_arriba" style="width:100px">Bruto</th>
        <th class="fondo_naranja borde_arriba borde_derecha" style="width:100px">Neto Enter</th>

    </tr>


    <tr>
        <td colspan="3" class="celda_vacia"></td>
        <td align="right" style="width: 60px; font-size: 10px; font-weight:bold" class="borde_arriba numero"><?php echo $this->numero($this->total_sumatoria['TOTAL_SUSCRIPTOS']) ?></td>

        <td align="right" style="width: 60px; font-size: 10px; font-weight:bold" class="borde_arriba numero"><?php echo $this->numero($total_foot['Total_Foot_Cobros_Hoy'],$this->totales[$carrier_numero['id_carrier']][$carrier_numero['numero']][$promocion_carrier_numero['id_promocion']]['decimal']) ?></td>
        <td align="right" style="width: 60px; font-size: 10px; font-weight:bold" class="borde_arriba numero"><?php echo $this->numero($total_foot['Total_Foot_Total_Hoy'],$this->totales[$carrier_numero['id_carrier']][$carrier_numero['numero']][$promocion_carrier_numero['id_promocion']]['decimal']) ?></td>
        <td align="right" style="width: 60px; font-size: 10px; font-weight:bold" class="borde_arriba numero"><?php echo $this->numero($total_foot['Total_Foot_Neto_Hoy'],$this->totales[$carrier_numero['id_carrier']][$carrier_numero['numero']][$promocion_carrier_numero['id_promocion']]['decimal']) ?></td>

        <td align="right" style="width: 60px; font-size: 10px; font-weight:bold" class="borde_arriba numero"><?php echo $this->numero($this->total_sumatoria['TOTAL_COBROS']) ?></td>
        <td align="right" style="width: 60px; font-size: 10px; font-weight:bold" class="borde_arriba numero"><?php echo $this->numero($this->total_sumatoria['TOTAL_BRUTO'], $this->total_sumatoria['decimal']) ?></td>
        <td align="right" style="width: 60px; font-size: 10px; font-weight:bold" class="borde_arriba borde_derecha numero"><?php echo $this->numero($this->total_sumatoria['TOTAL_NETO'], $this->total_sumatoria['decimal']) ?></td>
    </tr>

</table>